
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Category: 'Category',
  Award: 'Award',
  Application: 'Application',
  JuryApplication: 'JuryApplication',
  ApplicationAnswer: 'ApplicationAnswer',
  JuryApplicationFile: 'JuryApplicationFile',
  ApplicationFile: 'ApplicationFile',
  Payment: 'Payment'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  createdAt: 'createdAt'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const AwardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  categoryId: 'categoryId',
  createdAt: 'createdAt'
} as const

export type AwardScalarFieldEnum = (typeof AwardScalarFieldEnum)[keyof typeof AwardScalarFieldEnum]


export const ApplicationScalarFieldEnum = {
  id: 'id',
  fullName: 'fullName',
  email: 'email',
  phone: 'phone',
  country: 'country',
  stateProvince: 'stateProvince',
  city: 'city',
  professionalTitle: 'professionalTitle',
  yearsExperience: 'yearsExperience',
  membershipNumber: 'membershipNumber',
  membershipLevel: 'membershipLevel',
  websiteUrl: 'websiteUrl',
  socialUrl: 'socialUrl',
  reviewsUrl: 'reviewsUrl',
  heardAbout: 'heardAbout',
  categoryId: 'categoryId',
  awardId: 'awardId',
  status: 'status',
  paymentStatus: 'paymentStatus',
  submittedAt: 'submittedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ApplicationScalarFieldEnum = (typeof ApplicationScalarFieldEnum)[keyof typeof ApplicationScalarFieldEnum]


export const JuryApplicationScalarFieldEnum = {
  id: 'id',
  fullName: 'fullName',
  email: 'email',
  phone: 'phone',
  country: 'country',
  city: 'city',
  professionalTitle: 'professionalTitle',
  yearsExperience: 'yearsExperience',
  employerAffiliation: 'employerAffiliation',
  membershipStatus: 'membershipStatus',
  membershipLevel: 'membershipLevel',
  previousJudgingExperience: 'previousJudgingExperience',
  previousJudgingDetails: 'previousJudgingDetails',
  pastWinner: 'pastWinner',
  pastWinnerYear: 'pastWinnerYear',
  expertiseAreas: 'expertiseAreas',
  professionalBio: 'professionalBio',
  professionalWebsite: 'professionalWebsite',
  conflictDisclosure: 'conflictDisclosure',
  confidentialityAgreementAccepted: 'confidentialityAgreementAccepted',
  motivation: 'motivation',
  status: 'status',
  adminNotes: 'adminNotes',
  reviewedAt: 'reviewedAt',
  submittedAt: 'submittedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type JuryApplicationScalarFieldEnum = (typeof JuryApplicationScalarFieldEnum)[keyof typeof JuryApplicationScalarFieldEnum]


export const ApplicationAnswerScalarFieldEnum = {
  id: 'id',
  applicationId: 'applicationId',
  fieldKey: 'fieldKey',
  valueText: 'valueText',
  valueNumber: 'valueNumber',
  valueBoolean: 'valueBoolean',
  valueJson: 'valueJson',
  createdAt: 'createdAt'
} as const

export type ApplicationAnswerScalarFieldEnum = (typeof ApplicationAnswerScalarFieldEnum)[keyof typeof ApplicationAnswerScalarFieldEnum]


export const JuryApplicationFileScalarFieldEnum = {
  id: 'id',
  juryApplicationId: 'juryApplicationId',
  fieldKey: 'fieldKey',
  fileName: 'fileName',
  mimeType: 'mimeType',
  fileSize: 'fileSize',
  storageKey: 'storageKey',
  createdAt: 'createdAt'
} as const

export type JuryApplicationFileScalarFieldEnum = (typeof JuryApplicationFileScalarFieldEnum)[keyof typeof JuryApplicationFileScalarFieldEnum]


export const ApplicationFileScalarFieldEnum = {
  id: 'id',
  applicationId: 'applicationId',
  fieldKey: 'fieldKey',
  fileName: 'fileName',
  fileUrl: 'fileUrl',
  mimeType: 'mimeType',
  fileSize: 'fileSize',
  createdAt: 'createdAt'
} as const

export type ApplicationFileScalarFieldEnum = (typeof ApplicationFileScalarFieldEnum)[keyof typeof ApplicationFileScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  applicationId: 'applicationId',
  stripeSessionId: 'stripeSessionId',
  stripePaymentIntentId: 'stripePaymentIntentId',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  paidAt: 'paidAt',
  createdAt: 'createdAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

