
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Award
 * 
 */
export type Award = Prisma.AwardModel
/**
 * Model Application
 * 
 */
export type Application = Prisma.ApplicationModel
/**
 * Model JuryApplication
 * 
 */
export type JuryApplication = Prisma.JuryApplicationModel
/**
 * Model ApplicationAnswer
 * 
 */
export type ApplicationAnswer = Prisma.ApplicationAnswerModel
/**
 * Model JuryApplicationFile
 * 
 */
export type JuryApplicationFile = Prisma.JuryApplicationFileModel
/**
 * Model ApplicationFile
 * 
 */
export type ApplicationFile = Prisma.ApplicationFileModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
