import type { Language } from "@/lib/i18n/translations";

const en = {
  modal: {
    eyebrow: "IBPA Beauty Award 2026",
    title: "Buy Tickets",
    close: "Close ticket dialog",
  },
  form: {
    discount: {
      permanent: "Permanent 30",
      earlyBird: "Early Bird",
      pricing: "Pricing",
      suffix: "off forum passes. Gala Dinner and Special Packet excluded.",
    },
    package: {
      title: "Choose your package",
      required: "Please select a ticket package.",
      oneDay: "1 Day",
      oneDaySubtitle: "Single day access",
      twoDays: "2 Days",
      twoDaysSubtitle: "Full forum access",
      special: "Special Packet",
      specialSubtitle: "2 days + Gala Dinner",
      specialTickets: "2 separate tickets · 2 people",
      comingSoon: "Coming Soon",
      bestValue: "Best Value",
    },
    gala: {
      title: "Add-on: Gala Dinner",
      description: "Evening Gala Dinner on Day 1",
      perPerson: "per person",
      included: "Included",
      add: "Add",
    },
    membership: {
      title: "Membership",
      memberLabel: "I am an IBPA Member",
      memberHint: "Member pricing applies to the complete order.",
      certLabel: "IBPA CERT Number",
      certRequired: "CERT number is required.",
      checking: "Verifying…",
      valid: "Valid IBPA member certificate",
      invalid: "Certificate not found or expired",
      error: "Could not verify right now",
    },
    promo: {
      unavailable: "Not available for this package",
      enter: "Enter code",
      fixed: "Special Packet pricing is fixed and excludes all sales and coupons.",
      eligible: "Promo codes apply to eligible forum passes only.",
    },
    summary: {
      title: "Order Summary",
      special: "Special Packet (2 separate tickets)",
      oneDay: "1-Day Forum Pass",
      twoDays: "2-Day Forum Pass",
      member: "Member",
      promoDiscount: "Promo discount",
      gala: "Gala Dinner add-on",
      specialIncludes: "Includes 2-day Forum access and Gala Dinner for both attendees. Fixed price; no discounts apply.",
      total: "Total",
    },
    attendee: {
      title: "Attendee",
      information: "Attendee Information",
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email",
      phone: "Phone Number",
      instagram: "Instagram",
      instagramPlaceholder: "@username or instagram.com/username",
      firstNameRequired: "First name is required.",
      lastNameRequired: "Last name is required.",
      emailRequired: "Email is required.",
      emailInvalid: "Enter a valid email.",
      phoneRequired: "Phone number is required.",
      instagramRequired: "Instagram is required.",
      instagramInvalid: "Enter a valid Instagram username or profile link.",
      secondHint: "Each attendee receives a separate ticket email and QR code. Both email addresses may be the same.",
    },
    errors: {
      specialComingSoon: "The Special Packet is coming soon.",
      certInvalid: "Your IBPA certificate number could not be verified.",
      certChecking: "Please wait while we verify your certificate number.",
      generic: "Something went wrong. Please try again.",
      network: "Network error. Please check your connection and try again.",
    },
    actions: {
      creatingCheckout: "Creating your checkout…",
      verifyingCertificate: "Verifying certificate…",
      continuePayment: "Continue to Payment",
      secureCheckout: "Secure checkout powered by Stripe",
    },
  },
  pricing: {
    specialEyebrow: "Special Package",
    specialTitle: "Special Packet",
    specialDescription: "2-day Forum passes and Gala Dinner for two people.",
    new: "New",
    comingSoon: "Coming Soon",
    members: "IBPA Members",
    guests: "Guests",
    buy: "Buy",
    permanent: "Permanent 30",
    earlyBird: "Early Bird",
    off: "off",
  },
};

const ru: typeof en = {
  modal: {
    eyebrow: "IBPA Beauty Award 2026",
    title: "Купить билеты",
    close: "Закрыть окно покупки билетов",
  },
  form: {
    discount: {
      permanent: "Постоянная скидка 30%",
      earlyBird: "Ранняя регистрация",
      pricing: "Цена",
      suffix: "скидка на билеты форума. Гала-ужин и специальный пакет не участвуют.",
    },
    package: {
      title: "Выберите пакет",
      required: "Выберите пакет билетов.",
      oneDay: "1 день",
      oneDaySubtitle: "Доступ на один день",
      twoDays: "2 дня",
      twoDaysSubtitle: "Полный доступ к форуму",
      special: "Специальный пакет",
      specialSubtitle: "2 дня + гала-ужин",
      specialTickets: "2 отдельных билета · 2 человека",
      comingSoon: "Скоро",
      bestValue: "Выгодно",
    },
    gala: {
      title: "Дополнительно: гала-ужин",
      description: "Вечерний гала-ужин в первый день",
      perPerson: "за человека",
      included: "Включено",
      add: "Добавить",
    },
    membership: {
      title: "Членство",
      memberLabel: "Я являюсь участником IBPA",
      memberHint: "Цена для участников применяется ко всему заказу.",
      certLabel: "Номер сертификата IBPA",
      certRequired: "Укажите номер сертификата.",
      checking: "Проверяем…",
      valid: "Сертификат участника IBPA подтверждён",
      invalid: "Сертификат не найден или истёк",
      error: "Сейчас не удалось выполнить проверку",
    },
    promo: {
      unavailable: "Недоступно для этого пакета",
      enter: "Введите код",
      fixed: "Цена специального пакета фиксирована; скидки и промокоды не применяются.",
      eligible: "Промокоды действуют только на подходящие билеты форума.",
    },
    summary: {
      title: "Ваш заказ",
      special: "Специальный пакет (2 отдельных билета)",
      oneDay: "Билет на 1 день форума",
      twoDays: "Билет на 2 дня форума",
      member: "Участник",
      promoDiscount: "Скидка по промокоду",
      gala: "Гала-ужин",
      specialIncludes: "Включает доступ на 2 дня форума и гала-ужин для обоих гостей. Фиксированная цена без дополнительных скидок.",
      total: "Итого",
    },
    attendee: {
      title: "Гость",
      information: "Данные гостя",
      firstName: "Имя",
      lastName: "Фамилия",
      email: "Email",
      phone: "Номер телефона",
      instagram: "Instagram",
      instagramPlaceholder: "@имя или instagram.com/имя",
      firstNameRequired: "Укажите имя.",
      lastNameRequired: "Укажите фамилию.",
      emailRequired: "Укажите email.",
      emailInvalid: "Введите корректный email.",
      phoneRequired: "Укажите номер телефона.",
      instagramRequired: "Укажите Instagram.",
      instagramInvalid: "Введите корректное имя пользователя или ссылку Instagram.",
      secondHint: "Каждый гость получит отдельный билет и QR-код по email. Адреса email могут совпадать.",
    },
    errors: {
      specialComingSoon: "Специальный пакет скоро появится.",
      certInvalid: "Не удалось подтвердить номер сертификата IBPA.",
      certChecking: "Подождите, пока мы проверим номер сертификата.",
      generic: "Что-то пошло не так. Попробуйте ещё раз.",
      network: "Ошибка сети. Проверьте подключение и повторите попытку.",
    },
    actions: {
      creatingCheckout: "Создаём заказ…",
      verifyingCertificate: "Проверяем сертификат…",
      continuePayment: "Перейти к оплате",
      secureCheckout: "Безопасная оплата через Stripe",
    },
  },
  pricing: {
    specialEyebrow: "Специальное предложение",
    specialTitle: "Специальный пакет",
    specialDescription: "Два билета на 2 дня форума и гала-ужин для двух человек.",
    new: "Новинка",
    comingSoon: "Скоро",
    members: "Участники IBPA",
    guests: "Гости",
    buy: "Купить",
    permanent: "Постоянная скидка 30%",
    earlyBird: "Ранняя регистрация",
    off: "скидка",
  },
};

const ua: typeof en = {
  modal: {
    eyebrow: "IBPA Beauty Award 2026",
    title: "Купити квитки",
    close: "Закрити вікно придбання квитків",
  },
  form: {
    discount: {
      permanent: "Постійна знижка 30%",
      earlyBird: "Рання реєстрація",
      pricing: "Ціна",
      suffix: "знижка на квитки форуму. Гала-вечеря та спеціальний пакет не беруть участі.",
    },
    package: {
      title: "Оберіть пакет",
      required: "Оберіть пакет квитків.",
      oneDay: "1 день",
      oneDaySubtitle: "Доступ на один день",
      twoDays: "2 дні",
      twoDaysSubtitle: "Повний доступ до форуму",
      special: "Спеціальний пакет",
      specialSubtitle: "2 дні + гала-вечеря",
      specialTickets: "2 окремі квитки · 2 особи",
      comingSoon: "Незабаром",
      bestValue: "Вигідно",
    },
    gala: {
      title: "Додатково: гала-вечеря",
      description: "Вечірня гала-вечеря у перший день",
      perPerson: "за особу",
      included: "Включено",
      add: "Додати",
    },
    membership: {
      title: "Членство",
      memberLabel: "Я є учасником IBPA",
      memberHint: "Ціна для учасників застосовується до всього замовлення.",
      certLabel: "Номер сертифіката IBPA",
      certRequired: "Укажіть номер сертифіката.",
      checking: "Перевіряємо…",
      valid: "Сертифікат учасника IBPA підтверджено",
      invalid: "Сертифікат не знайдено або його термін минув",
      error: "Зараз не вдалося виконати перевірку",
    },
    promo: {
      unavailable: "Недоступно для цього пакета",
      enter: "Введіть код",
      fixed: "Ціна спеціального пакета фіксована; знижки та промокоди не застосовуються.",
      eligible: "Промокоди діють лише на відповідні квитки форуму.",
    },
    summary: {
      title: "Ваше замовлення",
      special: "Спеціальний пакет (2 окремі квитки)",
      oneDay: "Квиток на 1 день форуму",
      twoDays: "Квиток на 2 дні форуму",
      member: "Учасник",
      promoDiscount: "Знижка за промокодом",
      gala: "Гала-вечеря",
      specialIncludes: "Включає доступ на 2 дні форуму та гала-вечерю для обох гостей. Фіксована ціна без додаткових знижок.",
      total: "Разом",
    },
    attendee: {
      title: "Гість",
      information: "Дані гостя",
      firstName: "Ім’я",
      lastName: "Прізвище",
      email: "Email",
      phone: "Номер телефону",
      instagram: "Instagram",
      instagramPlaceholder: "@ім’я або instagram.com/ім’я",
      firstNameRequired: "Укажіть ім’я.",
      lastNameRequired: "Укажіть прізвище.",
      emailRequired: "Укажіть email.",
      emailInvalid: "Введіть коректний email.",
      phoneRequired: "Укажіть номер телефону.",
      instagramRequired: "Укажіть Instagram.",
      instagramInvalid: "Введіть коректне ім’я користувача або посилання Instagram.",
      secondHint: "Кожен гість отримає окремий квиток і QR-код електронною поштою. Адреси email можуть збігатися.",
    },
    errors: {
      specialComingSoon: "Спеціальний пакет незабаром з’явиться.",
      certInvalid: "Не вдалося підтвердити номер сертифіката IBPA.",
      certChecking: "Зачекайте, поки ми перевіримо номер сертифіката.",
      generic: "Щось пішло не так. Спробуйте ще раз.",
      network: "Помилка мережі. Перевірте з’єднання та повторіть спробу.",
    },
    actions: {
      creatingCheckout: "Створюємо замовлення…",
      verifyingCertificate: "Перевіряємо сертифікат…",
      continuePayment: "Перейти до оплати",
      secureCheckout: "Безпечна оплата через Stripe",
    },
  },
  pricing: {
    specialEyebrow: "Спеціальна пропозиція",
    specialTitle: "Спеціальний пакет",
    specialDescription: "Два квитки на 2 дні форуму та гала-вечеря для двох осіб.",
    new: "Новинка",
    comingSoon: "Незабаром",
    members: "Учасники IBPA",
    guests: "Гості",
    buy: "Купити",
    permanent: "Постійна знижка 30%",
    earlyBird: "Рання реєстрація",
    off: "знижка",
  },
};

export const ticketTranslations: Record<Language, typeof en> = { en, ru, ua };

export type TicketTranslation = typeof en;
