
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ApplicationAnswer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ApplicationAnswer
 * 
 */
export type ApplicationAnswerModel = runtime.Types.Result.DefaultSelection<Prisma.$ApplicationAnswerPayload>

export type AggregateApplicationAnswer = {
  _count: ApplicationAnswerCountAggregateOutputType | null
  _avg: ApplicationAnswerAvgAggregateOutputType | null
  _sum: ApplicationAnswerSumAggregateOutputType | null
  _min: ApplicationAnswerMinAggregateOutputType | null
  _max: ApplicationAnswerMaxAggregateOutputType | null
}

export type ApplicationAnswerAvgAggregateOutputType = {
  valueNumber: number | null
}

export type ApplicationAnswerSumAggregateOutputType = {
  valueNumber: number | null
}

export type ApplicationAnswerMinAggregateOutputType = {
  id: string | null
  applicationId: string | null
  fieldKey: string | null
  valueText: string | null
  valueNumber: number | null
  valueBoolean: boolean | null
  createdAt: Date | null
}

export type ApplicationAnswerMaxAggregateOutputType = {
  id: string | null
  applicationId: string | null
  fieldKey: string | null
  valueText: string | null
  valueNumber: number | null
  valueBoolean: boolean | null
  createdAt: Date | null
}

export type ApplicationAnswerCountAggregateOutputType = {
  id: number
  applicationId: number
  fieldKey: number
  valueText: number
  valueNumber: number
  valueBoolean: number
  valueJson: number
  createdAt: number
  _all: number
}


export type ApplicationAnswerAvgAggregateInputType = {
  valueNumber?: true
}

export type ApplicationAnswerSumAggregateInputType = {
  valueNumber?: true
}

export type ApplicationAnswerMinAggregateInputType = {
  id?: true
  applicationId?: true
  fieldKey?: true
  valueText?: true
  valueNumber?: true
  valueBoolean?: true
  createdAt?: true
}

export type ApplicationAnswerMaxAggregateInputType = {
  id?: true
  applicationId?: true
  fieldKey?: true
  valueText?: true
  valueNumber?: true
  valueBoolean?: true
  createdAt?: true
}

export type ApplicationAnswerCountAggregateInputType = {
  id?: true
  applicationId?: true
  fieldKey?: true
  valueText?: true
  valueNumber?: true
  valueBoolean?: true
  valueJson?: true
  createdAt?: true
  _all?: true
}

export type ApplicationAnswerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApplicationAnswer to aggregate.
   */
  where?: Prisma.ApplicationAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationAnswers to fetch.
   */
  orderBy?: Prisma.ApplicationAnswerOrderByWithRelationInput | Prisma.ApplicationAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApplicationAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ApplicationAnswers
  **/
  _count?: true | ApplicationAnswerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ApplicationAnswerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ApplicationAnswerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApplicationAnswerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApplicationAnswerMaxAggregateInputType
}

export type GetApplicationAnswerAggregateType<T extends ApplicationAnswerAggregateArgs> = {
      [P in keyof T & keyof AggregateApplicationAnswer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApplicationAnswer[P]>
    : Prisma.GetScalarType<T[P], AggregateApplicationAnswer[P]>
}




export type ApplicationAnswerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApplicationAnswerWhereInput
  orderBy?: Prisma.ApplicationAnswerOrderByWithAggregationInput | Prisma.ApplicationAnswerOrderByWithAggregationInput[]
  by: Prisma.ApplicationAnswerScalarFieldEnum[] | Prisma.ApplicationAnswerScalarFieldEnum
  having?: Prisma.ApplicationAnswerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApplicationAnswerCountAggregateInputType | true
  _avg?: ApplicationAnswerAvgAggregateInputType
  _sum?: ApplicationAnswerSumAggregateInputType
  _min?: ApplicationAnswerMinAggregateInputType
  _max?: ApplicationAnswerMaxAggregateInputType
}

export type ApplicationAnswerGroupByOutputType = {
  id: string
  applicationId: string
  fieldKey: string
  valueText: string | null
  valueNumber: number | null
  valueBoolean: boolean | null
  valueJson: runtime.JsonValue | null
  createdAt: Date
  _count: ApplicationAnswerCountAggregateOutputType | null
  _avg: ApplicationAnswerAvgAggregateOutputType | null
  _sum: ApplicationAnswerSumAggregateOutputType | null
  _min: ApplicationAnswerMinAggregateOutputType | null
  _max: ApplicationAnswerMaxAggregateOutputType | null
}

export type GetApplicationAnswerGroupByPayload<T extends ApplicationAnswerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApplicationAnswerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApplicationAnswerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApplicationAnswerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApplicationAnswerGroupByOutputType[P]>
      }
    >
  >



export type ApplicationAnswerWhereInput = {
  AND?: Prisma.ApplicationAnswerWhereInput | Prisma.ApplicationAnswerWhereInput[]
  OR?: Prisma.ApplicationAnswerWhereInput[]
  NOT?: Prisma.ApplicationAnswerWhereInput | Prisma.ApplicationAnswerWhereInput[]
  id?: Prisma.StringFilter<"ApplicationAnswer"> | string
  applicationId?: Prisma.StringFilter<"ApplicationAnswer"> | string
  fieldKey?: Prisma.StringFilter<"ApplicationAnswer"> | string
  valueText?: Prisma.StringNullableFilter<"ApplicationAnswer"> | string | null
  valueNumber?: Prisma.IntNullableFilter<"ApplicationAnswer"> | number | null
  valueBoolean?: Prisma.BoolNullableFilter<"ApplicationAnswer"> | boolean | null
  valueJson?: Prisma.JsonNullableFilter<"ApplicationAnswer">
  createdAt?: Prisma.DateTimeFilter<"ApplicationAnswer"> | Date | string
  application?: Prisma.XOR<Prisma.ApplicationScalarRelationFilter, Prisma.ApplicationWhereInput>
}

export type ApplicationAnswerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  valueText?: Prisma.SortOrderInput | Prisma.SortOrder
  valueNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  valueBoolean?: Prisma.SortOrderInput | Prisma.SortOrder
  valueJson?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  application?: Prisma.ApplicationOrderByWithRelationInput
}

export type ApplicationAnswerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ApplicationAnswerWhereInput | Prisma.ApplicationAnswerWhereInput[]
  OR?: Prisma.ApplicationAnswerWhereInput[]
  NOT?: Prisma.ApplicationAnswerWhereInput | Prisma.ApplicationAnswerWhereInput[]
  applicationId?: Prisma.StringFilter<"ApplicationAnswer"> | string
  fieldKey?: Prisma.StringFilter<"ApplicationAnswer"> | string
  valueText?: Prisma.StringNullableFilter<"ApplicationAnswer"> | string | null
  valueNumber?: Prisma.IntNullableFilter<"ApplicationAnswer"> | number | null
  valueBoolean?: Prisma.BoolNullableFilter<"ApplicationAnswer"> | boolean | null
  valueJson?: Prisma.JsonNullableFilter<"ApplicationAnswer">
  createdAt?: Prisma.DateTimeFilter<"ApplicationAnswer"> | Date | string
  application?: Prisma.XOR<Prisma.ApplicationScalarRelationFilter, Prisma.ApplicationWhereInput>
}, "id">

export type ApplicationAnswerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  valueText?: Prisma.SortOrderInput | Prisma.SortOrder
  valueNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  valueBoolean?: Prisma.SortOrderInput | Prisma.SortOrder
  valueJson?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ApplicationAnswerCountOrderByAggregateInput
  _avg?: Prisma.ApplicationAnswerAvgOrderByAggregateInput
  _max?: Prisma.ApplicationAnswerMaxOrderByAggregateInput
  _min?: Prisma.ApplicationAnswerMinOrderByAggregateInput
  _sum?: Prisma.ApplicationAnswerSumOrderByAggregateInput
}

export type ApplicationAnswerScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApplicationAnswerScalarWhereWithAggregatesInput | Prisma.ApplicationAnswerScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApplicationAnswerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApplicationAnswerScalarWhereWithAggregatesInput | Prisma.ApplicationAnswerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ApplicationAnswer"> | string
  applicationId?: Prisma.StringWithAggregatesFilter<"ApplicationAnswer"> | string
  fieldKey?: Prisma.StringWithAggregatesFilter<"ApplicationAnswer"> | string
  valueText?: Prisma.StringNullableWithAggregatesFilter<"ApplicationAnswer"> | string | null
  valueNumber?: Prisma.IntNullableWithAggregatesFilter<"ApplicationAnswer"> | number | null
  valueBoolean?: Prisma.BoolNullableWithAggregatesFilter<"ApplicationAnswer"> | boolean | null
  valueJson?: Prisma.JsonNullableWithAggregatesFilter<"ApplicationAnswer">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ApplicationAnswer"> | Date | string
}

export type ApplicationAnswerCreateInput = {
  id?: string
  fieldKey: string
  valueText?: string | null
  valueNumber?: number | null
  valueBoolean?: boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  application: Prisma.ApplicationCreateNestedOneWithoutAnswersInput
}

export type ApplicationAnswerUncheckedCreateInput = {
  id?: string
  applicationId: string
  fieldKey: string
  valueText?: string | null
  valueNumber?: number | null
  valueBoolean?: boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ApplicationAnswerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  valueText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valueNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  valueBoolean?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  application?: Prisma.ApplicationUpdateOneRequiredWithoutAnswersNestedInput
}

export type ApplicationAnswerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  valueText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valueNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  valueBoolean?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationAnswerCreateManyInput = {
  id?: string
  applicationId: string
  fieldKey: string
  valueText?: string | null
  valueNumber?: number | null
  valueBoolean?: boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ApplicationAnswerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  valueText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valueNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  valueBoolean?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationAnswerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  valueText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valueNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  valueBoolean?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationAnswerListRelationFilter = {
  every?: Prisma.ApplicationAnswerWhereInput
  some?: Prisma.ApplicationAnswerWhereInput
  none?: Prisma.ApplicationAnswerWhereInput
}

export type ApplicationAnswerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ApplicationAnswerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  valueText?: Prisma.SortOrder
  valueNumber?: Prisma.SortOrder
  valueBoolean?: Prisma.SortOrder
  valueJson?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ApplicationAnswerAvgOrderByAggregateInput = {
  valueNumber?: Prisma.SortOrder
}

export type ApplicationAnswerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  valueText?: Prisma.SortOrder
  valueNumber?: Prisma.SortOrder
  valueBoolean?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ApplicationAnswerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  valueText?: Prisma.SortOrder
  valueNumber?: Prisma.SortOrder
  valueBoolean?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ApplicationAnswerSumOrderByAggregateInput = {
  valueNumber?: Prisma.SortOrder
}

export type ApplicationAnswerCreateNestedManyWithoutApplicationInput = {
  create?: Prisma.XOR<Prisma.ApplicationAnswerCreateWithoutApplicationInput, Prisma.ApplicationAnswerUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationAnswerCreateWithoutApplicationInput[] | Prisma.ApplicationAnswerUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationAnswerCreateOrConnectWithoutApplicationInput | Prisma.ApplicationAnswerCreateOrConnectWithoutApplicationInput[]
  createMany?: Prisma.ApplicationAnswerCreateManyApplicationInputEnvelope
  connect?: Prisma.ApplicationAnswerWhereUniqueInput | Prisma.ApplicationAnswerWhereUniqueInput[]
}

export type ApplicationAnswerUncheckedCreateNestedManyWithoutApplicationInput = {
  create?: Prisma.XOR<Prisma.ApplicationAnswerCreateWithoutApplicationInput, Prisma.ApplicationAnswerUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationAnswerCreateWithoutApplicationInput[] | Prisma.ApplicationAnswerUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationAnswerCreateOrConnectWithoutApplicationInput | Prisma.ApplicationAnswerCreateOrConnectWithoutApplicationInput[]
  createMany?: Prisma.ApplicationAnswerCreateManyApplicationInputEnvelope
  connect?: Prisma.ApplicationAnswerWhereUniqueInput | Prisma.ApplicationAnswerWhereUniqueInput[]
}

export type ApplicationAnswerUpdateManyWithoutApplicationNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationAnswerCreateWithoutApplicationInput, Prisma.ApplicationAnswerUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationAnswerCreateWithoutApplicationInput[] | Prisma.ApplicationAnswerUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationAnswerCreateOrConnectWithoutApplicationInput | Prisma.ApplicationAnswerCreateOrConnectWithoutApplicationInput[]
  upsert?: Prisma.ApplicationAnswerUpsertWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationAnswerUpsertWithWhereUniqueWithoutApplicationInput[]
  createMany?: Prisma.ApplicationAnswerCreateManyApplicationInputEnvelope
  set?: Prisma.ApplicationAnswerWhereUniqueInput | Prisma.ApplicationAnswerWhereUniqueInput[]
  disconnect?: Prisma.ApplicationAnswerWhereUniqueInput | Prisma.ApplicationAnswerWhereUniqueInput[]
  delete?: Prisma.ApplicationAnswerWhereUniqueInput | Prisma.ApplicationAnswerWhereUniqueInput[]
  connect?: Prisma.ApplicationAnswerWhereUniqueInput | Prisma.ApplicationAnswerWhereUniqueInput[]
  update?: Prisma.ApplicationAnswerUpdateWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationAnswerUpdateWithWhereUniqueWithoutApplicationInput[]
  updateMany?: Prisma.ApplicationAnswerUpdateManyWithWhereWithoutApplicationInput | Prisma.ApplicationAnswerUpdateManyWithWhereWithoutApplicationInput[]
  deleteMany?: Prisma.ApplicationAnswerScalarWhereInput | Prisma.ApplicationAnswerScalarWhereInput[]
}

export type ApplicationAnswerUncheckedUpdateManyWithoutApplicationNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationAnswerCreateWithoutApplicationInput, Prisma.ApplicationAnswerUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationAnswerCreateWithoutApplicationInput[] | Prisma.ApplicationAnswerUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationAnswerCreateOrConnectWithoutApplicationInput | Prisma.ApplicationAnswerCreateOrConnectWithoutApplicationInput[]
  upsert?: Prisma.ApplicationAnswerUpsertWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationAnswerUpsertWithWhereUniqueWithoutApplicationInput[]
  createMany?: Prisma.ApplicationAnswerCreateManyApplicationInputEnvelope
  set?: Prisma.ApplicationAnswerWhereUniqueInput | Prisma.ApplicationAnswerWhereUniqueInput[]
  disconnect?: Prisma.ApplicationAnswerWhereUniqueInput | Prisma.ApplicationAnswerWhereUniqueInput[]
  delete?: Prisma.ApplicationAnswerWhereUniqueInput | Prisma.ApplicationAnswerWhereUniqueInput[]
  connect?: Prisma.ApplicationAnswerWhereUniqueInput | Prisma.ApplicationAnswerWhereUniqueInput[]
  update?: Prisma.ApplicationAnswerUpdateWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationAnswerUpdateWithWhereUniqueWithoutApplicationInput[]
  updateMany?: Prisma.ApplicationAnswerUpdateManyWithWhereWithoutApplicationInput | Prisma.ApplicationAnswerUpdateManyWithWhereWithoutApplicationInput[]
  deleteMany?: Prisma.ApplicationAnswerScalarWhereInput | Prisma.ApplicationAnswerScalarWhereInput[]
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type ApplicationAnswerCreateWithoutApplicationInput = {
  id?: string
  fieldKey: string
  valueText?: string | null
  valueNumber?: number | null
  valueBoolean?: boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ApplicationAnswerUncheckedCreateWithoutApplicationInput = {
  id?: string
  fieldKey: string
  valueText?: string | null
  valueNumber?: number | null
  valueBoolean?: boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ApplicationAnswerCreateOrConnectWithoutApplicationInput = {
  where: Prisma.ApplicationAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.ApplicationAnswerCreateWithoutApplicationInput, Prisma.ApplicationAnswerUncheckedCreateWithoutApplicationInput>
}

export type ApplicationAnswerCreateManyApplicationInputEnvelope = {
  data: Prisma.ApplicationAnswerCreateManyApplicationInput | Prisma.ApplicationAnswerCreateManyApplicationInput[]
  skipDuplicates?: boolean
}

export type ApplicationAnswerUpsertWithWhereUniqueWithoutApplicationInput = {
  where: Prisma.ApplicationAnswerWhereUniqueInput
  update: Prisma.XOR<Prisma.ApplicationAnswerUpdateWithoutApplicationInput, Prisma.ApplicationAnswerUncheckedUpdateWithoutApplicationInput>
  create: Prisma.XOR<Prisma.ApplicationAnswerCreateWithoutApplicationInput, Prisma.ApplicationAnswerUncheckedCreateWithoutApplicationInput>
}

export type ApplicationAnswerUpdateWithWhereUniqueWithoutApplicationInput = {
  where: Prisma.ApplicationAnswerWhereUniqueInput
  data: Prisma.XOR<Prisma.ApplicationAnswerUpdateWithoutApplicationInput, Prisma.ApplicationAnswerUncheckedUpdateWithoutApplicationInput>
}

export type ApplicationAnswerUpdateManyWithWhereWithoutApplicationInput = {
  where: Prisma.ApplicationAnswerScalarWhereInput
  data: Prisma.XOR<Prisma.ApplicationAnswerUpdateManyMutationInput, Prisma.ApplicationAnswerUncheckedUpdateManyWithoutApplicationInput>
}

export type ApplicationAnswerScalarWhereInput = {
  AND?: Prisma.ApplicationAnswerScalarWhereInput | Prisma.ApplicationAnswerScalarWhereInput[]
  OR?: Prisma.ApplicationAnswerScalarWhereInput[]
  NOT?: Prisma.ApplicationAnswerScalarWhereInput | Prisma.ApplicationAnswerScalarWhereInput[]
  id?: Prisma.StringFilter<"ApplicationAnswer"> | string
  applicationId?: Prisma.StringFilter<"ApplicationAnswer"> | string
  fieldKey?: Prisma.StringFilter<"ApplicationAnswer"> | string
  valueText?: Prisma.StringNullableFilter<"ApplicationAnswer"> | string | null
  valueNumber?: Prisma.IntNullableFilter<"ApplicationAnswer"> | number | null
  valueBoolean?: Prisma.BoolNullableFilter<"ApplicationAnswer"> | boolean | null
  valueJson?: Prisma.JsonNullableFilter<"ApplicationAnswer">
  createdAt?: Prisma.DateTimeFilter<"ApplicationAnswer"> | Date | string
}

export type ApplicationAnswerCreateManyApplicationInput = {
  id?: string
  fieldKey: string
  valueText?: string | null
  valueNumber?: number | null
  valueBoolean?: boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type ApplicationAnswerUpdateWithoutApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  valueText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valueNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  valueBoolean?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationAnswerUncheckedUpdateWithoutApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  valueText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valueNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  valueBoolean?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationAnswerUncheckedUpdateManyWithoutApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  valueText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  valueNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  valueBoolean?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  valueJson?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ApplicationAnswerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicationId?: boolean
  fieldKey?: boolean
  valueText?: boolean
  valueNumber?: boolean
  valueBoolean?: boolean
  valueJson?: boolean
  createdAt?: boolean
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["applicationAnswer"]>

export type ApplicationAnswerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicationId?: boolean
  fieldKey?: boolean
  valueText?: boolean
  valueNumber?: boolean
  valueBoolean?: boolean
  valueJson?: boolean
  createdAt?: boolean
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["applicationAnswer"]>

export type ApplicationAnswerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicationId?: boolean
  fieldKey?: boolean
  valueText?: boolean
  valueNumber?: boolean
  valueBoolean?: boolean
  valueJson?: boolean
  createdAt?: boolean
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["applicationAnswer"]>

export type ApplicationAnswerSelectScalar = {
  id?: boolean
  applicationId?: boolean
  fieldKey?: boolean
  valueText?: boolean
  valueNumber?: boolean
  valueBoolean?: boolean
  valueJson?: boolean
  createdAt?: boolean
}

export type ApplicationAnswerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "applicationId" | "fieldKey" | "valueText" | "valueNumber" | "valueBoolean" | "valueJson" | "createdAt", ExtArgs["result"]["applicationAnswer"]>
export type ApplicationAnswerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}
export type ApplicationAnswerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}
export type ApplicationAnswerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}

export type $ApplicationAnswerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ApplicationAnswer"
  objects: {
    application: Prisma.$ApplicationPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    applicationId: string
    fieldKey: string
    valueText: string | null
    valueNumber: number | null
    valueBoolean: boolean | null
    valueJson: runtime.JsonValue | null
    createdAt: Date
  }, ExtArgs["result"]["applicationAnswer"]>
  composites: {}
}

export type ApplicationAnswerGetPayload<S extends boolean | null | undefined | ApplicationAnswerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload, S>

export type ApplicationAnswerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApplicationAnswerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApplicationAnswerCountAggregateInputType | true
  }

export interface ApplicationAnswerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ApplicationAnswer'], meta: { name: 'ApplicationAnswer' } }
  /**
   * Find zero or one ApplicationAnswer that matches the filter.
   * @param {ApplicationAnswerFindUniqueArgs} args - Arguments to find a ApplicationAnswer
   * @example
   * // Get one ApplicationAnswer
   * const applicationAnswer = await prisma.applicationAnswer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApplicationAnswerFindUniqueArgs>(args: Prisma.SelectSubset<T, ApplicationAnswerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApplicationAnswerClient<runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ApplicationAnswer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApplicationAnswerFindUniqueOrThrowArgs} args - Arguments to find a ApplicationAnswer
   * @example
   * // Get one ApplicationAnswer
   * const applicationAnswer = await prisma.applicationAnswer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApplicationAnswerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApplicationAnswerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationAnswerClient<runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApplicationAnswer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationAnswerFindFirstArgs} args - Arguments to find a ApplicationAnswer
   * @example
   * // Get one ApplicationAnswer
   * const applicationAnswer = await prisma.applicationAnswer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApplicationAnswerFindFirstArgs>(args?: Prisma.SelectSubset<T, ApplicationAnswerFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApplicationAnswerClient<runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApplicationAnswer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationAnswerFindFirstOrThrowArgs} args - Arguments to find a ApplicationAnswer
   * @example
   * // Get one ApplicationAnswer
   * const applicationAnswer = await prisma.applicationAnswer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApplicationAnswerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApplicationAnswerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationAnswerClient<runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ApplicationAnswers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationAnswerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ApplicationAnswers
   * const applicationAnswers = await prisma.applicationAnswer.findMany()
   * 
   * // Get first 10 ApplicationAnswers
   * const applicationAnswers = await prisma.applicationAnswer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const applicationAnswerWithIdOnly = await prisma.applicationAnswer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApplicationAnswerFindManyArgs>(args?: Prisma.SelectSubset<T, ApplicationAnswerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ApplicationAnswer.
   * @param {ApplicationAnswerCreateArgs} args - Arguments to create a ApplicationAnswer.
   * @example
   * // Create one ApplicationAnswer
   * const ApplicationAnswer = await prisma.applicationAnswer.create({
   *   data: {
   *     // ... data to create a ApplicationAnswer
   *   }
   * })
   * 
   */
  create<T extends ApplicationAnswerCreateArgs>(args: Prisma.SelectSubset<T, ApplicationAnswerCreateArgs<ExtArgs>>): Prisma.Prisma__ApplicationAnswerClient<runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ApplicationAnswers.
   * @param {ApplicationAnswerCreateManyArgs} args - Arguments to create many ApplicationAnswers.
   * @example
   * // Create many ApplicationAnswers
   * const applicationAnswer = await prisma.applicationAnswer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApplicationAnswerCreateManyArgs>(args?: Prisma.SelectSubset<T, ApplicationAnswerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ApplicationAnswers and returns the data saved in the database.
   * @param {ApplicationAnswerCreateManyAndReturnArgs} args - Arguments to create many ApplicationAnswers.
   * @example
   * // Create many ApplicationAnswers
   * const applicationAnswer = await prisma.applicationAnswer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ApplicationAnswers and only return the `id`
   * const applicationAnswerWithIdOnly = await prisma.applicationAnswer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApplicationAnswerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApplicationAnswerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ApplicationAnswer.
   * @param {ApplicationAnswerDeleteArgs} args - Arguments to delete one ApplicationAnswer.
   * @example
   * // Delete one ApplicationAnswer
   * const ApplicationAnswer = await prisma.applicationAnswer.delete({
   *   where: {
   *     // ... filter to delete one ApplicationAnswer
   *   }
   * })
   * 
   */
  delete<T extends ApplicationAnswerDeleteArgs>(args: Prisma.SelectSubset<T, ApplicationAnswerDeleteArgs<ExtArgs>>): Prisma.Prisma__ApplicationAnswerClient<runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ApplicationAnswer.
   * @param {ApplicationAnswerUpdateArgs} args - Arguments to update one ApplicationAnswer.
   * @example
   * // Update one ApplicationAnswer
   * const applicationAnswer = await prisma.applicationAnswer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApplicationAnswerUpdateArgs>(args: Prisma.SelectSubset<T, ApplicationAnswerUpdateArgs<ExtArgs>>): Prisma.Prisma__ApplicationAnswerClient<runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ApplicationAnswers.
   * @param {ApplicationAnswerDeleteManyArgs} args - Arguments to filter ApplicationAnswers to delete.
   * @example
   * // Delete a few ApplicationAnswers
   * const { count } = await prisma.applicationAnswer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApplicationAnswerDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApplicationAnswerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApplicationAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationAnswerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ApplicationAnswers
   * const applicationAnswer = await prisma.applicationAnswer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApplicationAnswerUpdateManyArgs>(args: Prisma.SelectSubset<T, ApplicationAnswerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApplicationAnswers and returns the data updated in the database.
   * @param {ApplicationAnswerUpdateManyAndReturnArgs} args - Arguments to update many ApplicationAnswers.
   * @example
   * // Update many ApplicationAnswers
   * const applicationAnswer = await prisma.applicationAnswer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ApplicationAnswers and only return the `id`
   * const applicationAnswerWithIdOnly = await prisma.applicationAnswer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApplicationAnswerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApplicationAnswerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ApplicationAnswer.
   * @param {ApplicationAnswerUpsertArgs} args - Arguments to update or create a ApplicationAnswer.
   * @example
   * // Update or create a ApplicationAnswer
   * const applicationAnswer = await prisma.applicationAnswer.upsert({
   *   create: {
   *     // ... data to create a ApplicationAnswer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ApplicationAnswer we want to update
   *   }
   * })
   */
  upsert<T extends ApplicationAnswerUpsertArgs>(args: Prisma.SelectSubset<T, ApplicationAnswerUpsertArgs<ExtArgs>>): Prisma.Prisma__ApplicationAnswerClient<runtime.Types.Result.GetResult<Prisma.$ApplicationAnswerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ApplicationAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationAnswerCountArgs} args - Arguments to filter ApplicationAnswers to count.
   * @example
   * // Count the number of ApplicationAnswers
   * const count = await prisma.applicationAnswer.count({
   *   where: {
   *     // ... the filter for the ApplicationAnswers we want to count
   *   }
   * })
  **/
  count<T extends ApplicationAnswerCountArgs>(
    args?: Prisma.Subset<T, ApplicationAnswerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApplicationAnswerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ApplicationAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationAnswerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApplicationAnswerAggregateArgs>(args: Prisma.Subset<T, ApplicationAnswerAggregateArgs>): Prisma.PrismaPromise<GetApplicationAnswerAggregateType<T>>

  /**
   * Group by ApplicationAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationAnswerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApplicationAnswerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApplicationAnswerGroupByArgs['orderBy'] }
      : { orderBy?: ApplicationAnswerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApplicationAnswerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApplicationAnswerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ApplicationAnswer model
 */
readonly fields: ApplicationAnswerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ApplicationAnswer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApplicationAnswerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  application<T extends Prisma.ApplicationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ApplicationDefaultArgs<ExtArgs>>): Prisma.Prisma__ApplicationClient<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ApplicationAnswer model
 */
export interface ApplicationAnswerFieldRefs {
  readonly id: Prisma.FieldRef<"ApplicationAnswer", 'String'>
  readonly applicationId: Prisma.FieldRef<"ApplicationAnswer", 'String'>
  readonly fieldKey: Prisma.FieldRef<"ApplicationAnswer", 'String'>
  readonly valueText: Prisma.FieldRef<"ApplicationAnswer", 'String'>
  readonly valueNumber: Prisma.FieldRef<"ApplicationAnswer", 'Int'>
  readonly valueBoolean: Prisma.FieldRef<"ApplicationAnswer", 'Boolean'>
  readonly valueJson: Prisma.FieldRef<"ApplicationAnswer", 'Json'>
  readonly createdAt: Prisma.FieldRef<"ApplicationAnswer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ApplicationAnswer findUnique
 */
export type ApplicationAnswerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationAnswer to fetch.
   */
  where: Prisma.ApplicationAnswerWhereUniqueInput
}

/**
 * ApplicationAnswer findUniqueOrThrow
 */
export type ApplicationAnswerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationAnswer to fetch.
   */
  where: Prisma.ApplicationAnswerWhereUniqueInput
}

/**
 * ApplicationAnswer findFirst
 */
export type ApplicationAnswerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationAnswer to fetch.
   */
  where?: Prisma.ApplicationAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationAnswers to fetch.
   */
  orderBy?: Prisma.ApplicationAnswerOrderByWithRelationInput | Prisma.ApplicationAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApplicationAnswers.
   */
  cursor?: Prisma.ApplicationAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationAnswers.
   */
  distinct?: Prisma.ApplicationAnswerScalarFieldEnum | Prisma.ApplicationAnswerScalarFieldEnum[]
}

/**
 * ApplicationAnswer findFirstOrThrow
 */
export type ApplicationAnswerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationAnswer to fetch.
   */
  where?: Prisma.ApplicationAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationAnswers to fetch.
   */
  orderBy?: Prisma.ApplicationAnswerOrderByWithRelationInput | Prisma.ApplicationAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApplicationAnswers.
   */
  cursor?: Prisma.ApplicationAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationAnswers.
   */
  distinct?: Prisma.ApplicationAnswerScalarFieldEnum | Prisma.ApplicationAnswerScalarFieldEnum[]
}

/**
 * ApplicationAnswer findMany
 */
export type ApplicationAnswerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationAnswers to fetch.
   */
  where?: Prisma.ApplicationAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationAnswers to fetch.
   */
  orderBy?: Prisma.ApplicationAnswerOrderByWithRelationInput | Prisma.ApplicationAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ApplicationAnswers.
   */
  cursor?: Prisma.ApplicationAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationAnswers.
   */
  distinct?: Prisma.ApplicationAnswerScalarFieldEnum | Prisma.ApplicationAnswerScalarFieldEnum[]
}

/**
 * ApplicationAnswer create
 */
export type ApplicationAnswerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerInclude<ExtArgs> | null
  /**
   * The data needed to create a ApplicationAnswer.
   */
  data: Prisma.XOR<Prisma.ApplicationAnswerCreateInput, Prisma.ApplicationAnswerUncheckedCreateInput>
}

/**
 * ApplicationAnswer createMany
 */
export type ApplicationAnswerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ApplicationAnswers.
   */
  data: Prisma.ApplicationAnswerCreateManyInput | Prisma.ApplicationAnswerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ApplicationAnswer createManyAndReturn
 */
export type ApplicationAnswerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * The data used to create many ApplicationAnswers.
   */
  data: Prisma.ApplicationAnswerCreateManyInput | Prisma.ApplicationAnswerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ApplicationAnswer update
 */
export type ApplicationAnswerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerInclude<ExtArgs> | null
  /**
   * The data needed to update a ApplicationAnswer.
   */
  data: Prisma.XOR<Prisma.ApplicationAnswerUpdateInput, Prisma.ApplicationAnswerUncheckedUpdateInput>
  /**
   * Choose, which ApplicationAnswer to update.
   */
  where: Prisma.ApplicationAnswerWhereUniqueInput
}

/**
 * ApplicationAnswer updateMany
 */
export type ApplicationAnswerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ApplicationAnswers.
   */
  data: Prisma.XOR<Prisma.ApplicationAnswerUpdateManyMutationInput, Prisma.ApplicationAnswerUncheckedUpdateManyInput>
  /**
   * Filter which ApplicationAnswers to update
   */
  where?: Prisma.ApplicationAnswerWhereInput
  /**
   * Limit how many ApplicationAnswers to update.
   */
  limit?: number
}

/**
 * ApplicationAnswer updateManyAndReturn
 */
export type ApplicationAnswerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * The data used to update ApplicationAnswers.
   */
  data: Prisma.XOR<Prisma.ApplicationAnswerUpdateManyMutationInput, Prisma.ApplicationAnswerUncheckedUpdateManyInput>
  /**
   * Filter which ApplicationAnswers to update
   */
  where?: Prisma.ApplicationAnswerWhereInput
  /**
   * Limit how many ApplicationAnswers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ApplicationAnswer upsert
 */
export type ApplicationAnswerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerInclude<ExtArgs> | null
  /**
   * The filter to search for the ApplicationAnswer to update in case it exists.
   */
  where: Prisma.ApplicationAnswerWhereUniqueInput
  /**
   * In case the ApplicationAnswer found by the `where` argument doesn't exist, create a new ApplicationAnswer with this data.
   */
  create: Prisma.XOR<Prisma.ApplicationAnswerCreateInput, Prisma.ApplicationAnswerUncheckedCreateInput>
  /**
   * In case the ApplicationAnswer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApplicationAnswerUpdateInput, Prisma.ApplicationAnswerUncheckedUpdateInput>
}

/**
 * ApplicationAnswer delete
 */
export type ApplicationAnswerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerInclude<ExtArgs> | null
  /**
   * Filter which ApplicationAnswer to delete.
   */
  where: Prisma.ApplicationAnswerWhereUniqueInput
}

/**
 * ApplicationAnswer deleteMany
 */
export type ApplicationAnswerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApplicationAnswers to delete
   */
  where?: Prisma.ApplicationAnswerWhereInput
  /**
   * Limit how many ApplicationAnswers to delete.
   */
  limit?: number
}

/**
 * ApplicationAnswer without action
 */
export type ApplicationAnswerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationAnswer
   */
  select?: Prisma.ApplicationAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationAnswer
   */
  omit?: Prisma.ApplicationAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationAnswerInclude<ExtArgs> | null
}
