
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ApplicationFile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ApplicationFile
 * 
 */
export type ApplicationFileModel = runtime.Types.Result.DefaultSelection<Prisma.$ApplicationFilePayload>

export type AggregateApplicationFile = {
  _count: ApplicationFileCountAggregateOutputType | null
  _avg: ApplicationFileAvgAggregateOutputType | null
  _sum: ApplicationFileSumAggregateOutputType | null
  _min: ApplicationFileMinAggregateOutputType | null
  _max: ApplicationFileMaxAggregateOutputType | null
}

export type ApplicationFileAvgAggregateOutputType = {
  fileSize: number | null
}

export type ApplicationFileSumAggregateOutputType = {
  fileSize: number | null
}

export type ApplicationFileMinAggregateOutputType = {
  id: string | null
  applicationId: string | null
  fieldKey: string | null
  fileName: string | null
  fileUrl: string | null
  mimeType: string | null
  fileSize: number | null
  createdAt: Date | null
}

export type ApplicationFileMaxAggregateOutputType = {
  id: string | null
  applicationId: string | null
  fieldKey: string | null
  fileName: string | null
  fileUrl: string | null
  mimeType: string | null
  fileSize: number | null
  createdAt: Date | null
}

export type ApplicationFileCountAggregateOutputType = {
  id: number
  applicationId: number
  fieldKey: number
  fileName: number
  fileUrl: number
  mimeType: number
  fileSize: number
  createdAt: number
  _all: number
}


export type ApplicationFileAvgAggregateInputType = {
  fileSize?: true
}

export type ApplicationFileSumAggregateInputType = {
  fileSize?: true
}

export type ApplicationFileMinAggregateInputType = {
  id?: true
  applicationId?: true
  fieldKey?: true
  fileName?: true
  fileUrl?: true
  mimeType?: true
  fileSize?: true
  createdAt?: true
}

export type ApplicationFileMaxAggregateInputType = {
  id?: true
  applicationId?: true
  fieldKey?: true
  fileName?: true
  fileUrl?: true
  mimeType?: true
  fileSize?: true
  createdAt?: true
}

export type ApplicationFileCountAggregateInputType = {
  id?: true
  applicationId?: true
  fieldKey?: true
  fileName?: true
  fileUrl?: true
  mimeType?: true
  fileSize?: true
  createdAt?: true
  _all?: true
}

export type ApplicationFileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApplicationFile to aggregate.
   */
  where?: Prisma.ApplicationFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationFiles to fetch.
   */
  orderBy?: Prisma.ApplicationFileOrderByWithRelationInput | Prisma.ApplicationFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApplicationFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ApplicationFiles
  **/
  _count?: true | ApplicationFileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ApplicationFileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ApplicationFileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApplicationFileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApplicationFileMaxAggregateInputType
}

export type GetApplicationFileAggregateType<T extends ApplicationFileAggregateArgs> = {
      [P in keyof T & keyof AggregateApplicationFile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApplicationFile[P]>
    : Prisma.GetScalarType<T[P], AggregateApplicationFile[P]>
}




export type ApplicationFileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApplicationFileWhereInput
  orderBy?: Prisma.ApplicationFileOrderByWithAggregationInput | Prisma.ApplicationFileOrderByWithAggregationInput[]
  by: Prisma.ApplicationFileScalarFieldEnum[] | Prisma.ApplicationFileScalarFieldEnum
  having?: Prisma.ApplicationFileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApplicationFileCountAggregateInputType | true
  _avg?: ApplicationFileAvgAggregateInputType
  _sum?: ApplicationFileSumAggregateInputType
  _min?: ApplicationFileMinAggregateInputType
  _max?: ApplicationFileMaxAggregateInputType
}

export type ApplicationFileGroupByOutputType = {
  id: string
  applicationId: string
  fieldKey: string
  fileName: string
  fileUrl: string
  mimeType: string
  fileSize: number
  createdAt: Date
  _count: ApplicationFileCountAggregateOutputType | null
  _avg: ApplicationFileAvgAggregateOutputType | null
  _sum: ApplicationFileSumAggregateOutputType | null
  _min: ApplicationFileMinAggregateOutputType | null
  _max: ApplicationFileMaxAggregateOutputType | null
}

export type GetApplicationFileGroupByPayload<T extends ApplicationFileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApplicationFileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApplicationFileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApplicationFileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApplicationFileGroupByOutputType[P]>
      }
    >
  >



export type ApplicationFileWhereInput = {
  AND?: Prisma.ApplicationFileWhereInput | Prisma.ApplicationFileWhereInput[]
  OR?: Prisma.ApplicationFileWhereInput[]
  NOT?: Prisma.ApplicationFileWhereInput | Prisma.ApplicationFileWhereInput[]
  id?: Prisma.StringFilter<"ApplicationFile"> | string
  applicationId?: Prisma.StringFilter<"ApplicationFile"> | string
  fieldKey?: Prisma.StringFilter<"ApplicationFile"> | string
  fileName?: Prisma.StringFilter<"ApplicationFile"> | string
  fileUrl?: Prisma.StringFilter<"ApplicationFile"> | string
  mimeType?: Prisma.StringFilter<"ApplicationFile"> | string
  fileSize?: Prisma.IntFilter<"ApplicationFile"> | number
  createdAt?: Prisma.DateTimeFilter<"ApplicationFile"> | Date | string
  application?: Prisma.XOR<Prisma.ApplicationScalarRelationFilter, Prisma.ApplicationWhereInput>
}

export type ApplicationFileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  application?: Prisma.ApplicationOrderByWithRelationInput
}

export type ApplicationFileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ApplicationFileWhereInput | Prisma.ApplicationFileWhereInput[]
  OR?: Prisma.ApplicationFileWhereInput[]
  NOT?: Prisma.ApplicationFileWhereInput | Prisma.ApplicationFileWhereInput[]
  applicationId?: Prisma.StringFilter<"ApplicationFile"> | string
  fieldKey?: Prisma.StringFilter<"ApplicationFile"> | string
  fileName?: Prisma.StringFilter<"ApplicationFile"> | string
  fileUrl?: Prisma.StringFilter<"ApplicationFile"> | string
  mimeType?: Prisma.StringFilter<"ApplicationFile"> | string
  fileSize?: Prisma.IntFilter<"ApplicationFile"> | number
  createdAt?: Prisma.DateTimeFilter<"ApplicationFile"> | Date | string
  application?: Prisma.XOR<Prisma.ApplicationScalarRelationFilter, Prisma.ApplicationWhereInput>
}, "id">

export type ApplicationFileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ApplicationFileCountOrderByAggregateInput
  _avg?: Prisma.ApplicationFileAvgOrderByAggregateInput
  _max?: Prisma.ApplicationFileMaxOrderByAggregateInput
  _min?: Prisma.ApplicationFileMinOrderByAggregateInput
  _sum?: Prisma.ApplicationFileSumOrderByAggregateInput
}

export type ApplicationFileScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApplicationFileScalarWhereWithAggregatesInput | Prisma.ApplicationFileScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApplicationFileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApplicationFileScalarWhereWithAggregatesInput | Prisma.ApplicationFileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ApplicationFile"> | string
  applicationId?: Prisma.StringWithAggregatesFilter<"ApplicationFile"> | string
  fieldKey?: Prisma.StringWithAggregatesFilter<"ApplicationFile"> | string
  fileName?: Prisma.StringWithAggregatesFilter<"ApplicationFile"> | string
  fileUrl?: Prisma.StringWithAggregatesFilter<"ApplicationFile"> | string
  mimeType?: Prisma.StringWithAggregatesFilter<"ApplicationFile"> | string
  fileSize?: Prisma.IntWithAggregatesFilter<"ApplicationFile"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ApplicationFile"> | Date | string
}

export type ApplicationFileCreateInput = {
  id?: string
  fieldKey: string
  fileName: string
  fileUrl: string
  mimeType: string
  fileSize: number
  createdAt?: Date | string
  application: Prisma.ApplicationCreateNestedOneWithoutFilesInput
}

export type ApplicationFileUncheckedCreateInput = {
  id?: string
  applicationId: string
  fieldKey: string
  fileName: string
  fileUrl: string
  mimeType: string
  fileSize: number
  createdAt?: Date | string
}

export type ApplicationFileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  application?: Prisma.ApplicationUpdateOneRequiredWithoutFilesNestedInput
}

export type ApplicationFileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationFileCreateManyInput = {
  id?: string
  applicationId: string
  fieldKey: string
  fileName: string
  fileUrl: string
  mimeType: string
  fileSize: number
  createdAt?: Date | string
}

export type ApplicationFileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationFileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationFileListRelationFilter = {
  every?: Prisma.ApplicationFileWhereInput
  some?: Prisma.ApplicationFileWhereInput
  none?: Prisma.ApplicationFileWhereInput
}

export type ApplicationFileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ApplicationFileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ApplicationFileAvgOrderByAggregateInput = {
  fileSize?: Prisma.SortOrder
}

export type ApplicationFileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ApplicationFileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ApplicationFileSumOrderByAggregateInput = {
  fileSize?: Prisma.SortOrder
}

export type ApplicationFileCreateNestedManyWithoutApplicationInput = {
  create?: Prisma.XOR<Prisma.ApplicationFileCreateWithoutApplicationInput, Prisma.ApplicationFileUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationFileCreateWithoutApplicationInput[] | Prisma.ApplicationFileUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationFileCreateOrConnectWithoutApplicationInput | Prisma.ApplicationFileCreateOrConnectWithoutApplicationInput[]
  createMany?: Prisma.ApplicationFileCreateManyApplicationInputEnvelope
  connect?: Prisma.ApplicationFileWhereUniqueInput | Prisma.ApplicationFileWhereUniqueInput[]
}

export type ApplicationFileUncheckedCreateNestedManyWithoutApplicationInput = {
  create?: Prisma.XOR<Prisma.ApplicationFileCreateWithoutApplicationInput, Prisma.ApplicationFileUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationFileCreateWithoutApplicationInput[] | Prisma.ApplicationFileUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationFileCreateOrConnectWithoutApplicationInput | Prisma.ApplicationFileCreateOrConnectWithoutApplicationInput[]
  createMany?: Prisma.ApplicationFileCreateManyApplicationInputEnvelope
  connect?: Prisma.ApplicationFileWhereUniqueInput | Prisma.ApplicationFileWhereUniqueInput[]
}

export type ApplicationFileUpdateManyWithoutApplicationNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationFileCreateWithoutApplicationInput, Prisma.ApplicationFileUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationFileCreateWithoutApplicationInput[] | Prisma.ApplicationFileUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationFileCreateOrConnectWithoutApplicationInput | Prisma.ApplicationFileCreateOrConnectWithoutApplicationInput[]
  upsert?: Prisma.ApplicationFileUpsertWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationFileUpsertWithWhereUniqueWithoutApplicationInput[]
  createMany?: Prisma.ApplicationFileCreateManyApplicationInputEnvelope
  set?: Prisma.ApplicationFileWhereUniqueInput | Prisma.ApplicationFileWhereUniqueInput[]
  disconnect?: Prisma.ApplicationFileWhereUniqueInput | Prisma.ApplicationFileWhereUniqueInput[]
  delete?: Prisma.ApplicationFileWhereUniqueInput | Prisma.ApplicationFileWhereUniqueInput[]
  connect?: Prisma.ApplicationFileWhereUniqueInput | Prisma.ApplicationFileWhereUniqueInput[]
  update?: Prisma.ApplicationFileUpdateWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationFileUpdateWithWhereUniqueWithoutApplicationInput[]
  updateMany?: Prisma.ApplicationFileUpdateManyWithWhereWithoutApplicationInput | Prisma.ApplicationFileUpdateManyWithWhereWithoutApplicationInput[]
  deleteMany?: Prisma.ApplicationFileScalarWhereInput | Prisma.ApplicationFileScalarWhereInput[]
}

export type ApplicationFileUncheckedUpdateManyWithoutApplicationNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationFileCreateWithoutApplicationInput, Prisma.ApplicationFileUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationFileCreateWithoutApplicationInput[] | Prisma.ApplicationFileUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationFileCreateOrConnectWithoutApplicationInput | Prisma.ApplicationFileCreateOrConnectWithoutApplicationInput[]
  upsert?: Prisma.ApplicationFileUpsertWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationFileUpsertWithWhereUniqueWithoutApplicationInput[]
  createMany?: Prisma.ApplicationFileCreateManyApplicationInputEnvelope
  set?: Prisma.ApplicationFileWhereUniqueInput | Prisma.ApplicationFileWhereUniqueInput[]
  disconnect?: Prisma.ApplicationFileWhereUniqueInput | Prisma.ApplicationFileWhereUniqueInput[]
  delete?: Prisma.ApplicationFileWhereUniqueInput | Prisma.ApplicationFileWhereUniqueInput[]
  connect?: Prisma.ApplicationFileWhereUniqueInput | Prisma.ApplicationFileWhereUniqueInput[]
  update?: Prisma.ApplicationFileUpdateWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationFileUpdateWithWhereUniqueWithoutApplicationInput[]
  updateMany?: Prisma.ApplicationFileUpdateManyWithWhereWithoutApplicationInput | Prisma.ApplicationFileUpdateManyWithWhereWithoutApplicationInput[]
  deleteMany?: Prisma.ApplicationFileScalarWhereInput | Prisma.ApplicationFileScalarWhereInput[]
}

export type ApplicationFileCreateWithoutApplicationInput = {
  id?: string
  fieldKey: string
  fileName: string
  fileUrl: string
  mimeType: string
  fileSize: number
  createdAt?: Date | string
}

export type ApplicationFileUncheckedCreateWithoutApplicationInput = {
  id?: string
  fieldKey: string
  fileName: string
  fileUrl: string
  mimeType: string
  fileSize: number
  createdAt?: Date | string
}

export type ApplicationFileCreateOrConnectWithoutApplicationInput = {
  where: Prisma.ApplicationFileWhereUniqueInput
  create: Prisma.XOR<Prisma.ApplicationFileCreateWithoutApplicationInput, Prisma.ApplicationFileUncheckedCreateWithoutApplicationInput>
}

export type ApplicationFileCreateManyApplicationInputEnvelope = {
  data: Prisma.ApplicationFileCreateManyApplicationInput | Prisma.ApplicationFileCreateManyApplicationInput[]
  skipDuplicates?: boolean
}

export type ApplicationFileUpsertWithWhereUniqueWithoutApplicationInput = {
  where: Prisma.ApplicationFileWhereUniqueInput
  update: Prisma.XOR<Prisma.ApplicationFileUpdateWithoutApplicationInput, Prisma.ApplicationFileUncheckedUpdateWithoutApplicationInput>
  create: Prisma.XOR<Prisma.ApplicationFileCreateWithoutApplicationInput, Prisma.ApplicationFileUncheckedCreateWithoutApplicationInput>
}

export type ApplicationFileUpdateWithWhereUniqueWithoutApplicationInput = {
  where: Prisma.ApplicationFileWhereUniqueInput
  data: Prisma.XOR<Prisma.ApplicationFileUpdateWithoutApplicationInput, Prisma.ApplicationFileUncheckedUpdateWithoutApplicationInput>
}

export type ApplicationFileUpdateManyWithWhereWithoutApplicationInput = {
  where: Prisma.ApplicationFileScalarWhereInput
  data: Prisma.XOR<Prisma.ApplicationFileUpdateManyMutationInput, Prisma.ApplicationFileUncheckedUpdateManyWithoutApplicationInput>
}

export type ApplicationFileScalarWhereInput = {
  AND?: Prisma.ApplicationFileScalarWhereInput | Prisma.ApplicationFileScalarWhereInput[]
  OR?: Prisma.ApplicationFileScalarWhereInput[]
  NOT?: Prisma.ApplicationFileScalarWhereInput | Prisma.ApplicationFileScalarWhereInput[]
  id?: Prisma.StringFilter<"ApplicationFile"> | string
  applicationId?: Prisma.StringFilter<"ApplicationFile"> | string
  fieldKey?: Prisma.StringFilter<"ApplicationFile"> | string
  fileName?: Prisma.StringFilter<"ApplicationFile"> | string
  fileUrl?: Prisma.StringFilter<"ApplicationFile"> | string
  mimeType?: Prisma.StringFilter<"ApplicationFile"> | string
  fileSize?: Prisma.IntFilter<"ApplicationFile"> | number
  createdAt?: Prisma.DateTimeFilter<"ApplicationFile"> | Date | string
}

export type ApplicationFileCreateManyApplicationInput = {
  id?: string
  fieldKey: string
  fileName: string
  fileUrl: string
  mimeType: string
  fileSize: number
  createdAt?: Date | string
}

export type ApplicationFileUpdateWithoutApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationFileUncheckedUpdateWithoutApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationFileUncheckedUpdateManyWithoutApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ApplicationFileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicationId?: boolean
  fieldKey?: boolean
  fileName?: boolean
  fileUrl?: boolean
  mimeType?: boolean
  fileSize?: boolean
  createdAt?: boolean
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["applicationFile"]>

export type ApplicationFileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicationId?: boolean
  fieldKey?: boolean
  fileName?: boolean
  fileUrl?: boolean
  mimeType?: boolean
  fileSize?: boolean
  createdAt?: boolean
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["applicationFile"]>

export type ApplicationFileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicationId?: boolean
  fieldKey?: boolean
  fileName?: boolean
  fileUrl?: boolean
  mimeType?: boolean
  fileSize?: boolean
  createdAt?: boolean
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["applicationFile"]>

export type ApplicationFileSelectScalar = {
  id?: boolean
  applicationId?: boolean
  fieldKey?: boolean
  fileName?: boolean
  fileUrl?: boolean
  mimeType?: boolean
  fileSize?: boolean
  createdAt?: boolean
}

export type ApplicationFileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "applicationId" | "fieldKey" | "fileName" | "fileUrl" | "mimeType" | "fileSize" | "createdAt", ExtArgs["result"]["applicationFile"]>
export type ApplicationFileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}
export type ApplicationFileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}
export type ApplicationFileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.ApplicationDefaultArgs<ExtArgs>
}

export type $ApplicationFilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ApplicationFile"
  objects: {
    application: Prisma.$ApplicationPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    applicationId: string
    fieldKey: string
    fileName: string
    fileUrl: string
    mimeType: string
    fileSize: number
    createdAt: Date
  }, ExtArgs["result"]["applicationFile"]>
  composites: {}
}

export type ApplicationFileGetPayload<S extends boolean | null | undefined | ApplicationFileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload, S>

export type ApplicationFileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApplicationFileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApplicationFileCountAggregateInputType | true
  }

export interface ApplicationFileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ApplicationFile'], meta: { name: 'ApplicationFile' } }
  /**
   * Find zero or one ApplicationFile that matches the filter.
   * @param {ApplicationFileFindUniqueArgs} args - Arguments to find a ApplicationFile
   * @example
   * // Get one ApplicationFile
   * const applicationFile = await prisma.applicationFile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApplicationFileFindUniqueArgs>(args: Prisma.SelectSubset<T, ApplicationFileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ApplicationFile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApplicationFileFindUniqueOrThrowArgs} args - Arguments to find a ApplicationFile
   * @example
   * // Get one ApplicationFile
   * const applicationFile = await prisma.applicationFile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApplicationFileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApplicationFileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApplicationFile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationFileFindFirstArgs} args - Arguments to find a ApplicationFile
   * @example
   * // Get one ApplicationFile
   * const applicationFile = await prisma.applicationFile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApplicationFileFindFirstArgs>(args?: Prisma.SelectSubset<T, ApplicationFileFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApplicationFile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationFileFindFirstOrThrowArgs} args - Arguments to find a ApplicationFile
   * @example
   * // Get one ApplicationFile
   * const applicationFile = await prisma.applicationFile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApplicationFileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApplicationFileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ApplicationFiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationFileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ApplicationFiles
   * const applicationFiles = await prisma.applicationFile.findMany()
   * 
   * // Get first 10 ApplicationFiles
   * const applicationFiles = await prisma.applicationFile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const applicationFileWithIdOnly = await prisma.applicationFile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApplicationFileFindManyArgs>(args?: Prisma.SelectSubset<T, ApplicationFileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ApplicationFile.
   * @param {ApplicationFileCreateArgs} args - Arguments to create a ApplicationFile.
   * @example
   * // Create one ApplicationFile
   * const ApplicationFile = await prisma.applicationFile.create({
   *   data: {
   *     // ... data to create a ApplicationFile
   *   }
   * })
   * 
   */
  create<T extends ApplicationFileCreateArgs>(args: Prisma.SelectSubset<T, ApplicationFileCreateArgs<ExtArgs>>): Prisma.Prisma__ApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ApplicationFiles.
   * @param {ApplicationFileCreateManyArgs} args - Arguments to create many ApplicationFiles.
   * @example
   * // Create many ApplicationFiles
   * const applicationFile = await prisma.applicationFile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApplicationFileCreateManyArgs>(args?: Prisma.SelectSubset<T, ApplicationFileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ApplicationFiles and returns the data saved in the database.
   * @param {ApplicationFileCreateManyAndReturnArgs} args - Arguments to create many ApplicationFiles.
   * @example
   * // Create many ApplicationFiles
   * const applicationFile = await prisma.applicationFile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ApplicationFiles and only return the `id`
   * const applicationFileWithIdOnly = await prisma.applicationFile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApplicationFileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApplicationFileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ApplicationFile.
   * @param {ApplicationFileDeleteArgs} args - Arguments to delete one ApplicationFile.
   * @example
   * // Delete one ApplicationFile
   * const ApplicationFile = await prisma.applicationFile.delete({
   *   where: {
   *     // ... filter to delete one ApplicationFile
   *   }
   * })
   * 
   */
  delete<T extends ApplicationFileDeleteArgs>(args: Prisma.SelectSubset<T, ApplicationFileDeleteArgs<ExtArgs>>): Prisma.Prisma__ApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ApplicationFile.
   * @param {ApplicationFileUpdateArgs} args - Arguments to update one ApplicationFile.
   * @example
   * // Update one ApplicationFile
   * const applicationFile = await prisma.applicationFile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApplicationFileUpdateArgs>(args: Prisma.SelectSubset<T, ApplicationFileUpdateArgs<ExtArgs>>): Prisma.Prisma__ApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ApplicationFiles.
   * @param {ApplicationFileDeleteManyArgs} args - Arguments to filter ApplicationFiles to delete.
   * @example
   * // Delete a few ApplicationFiles
   * const { count } = await prisma.applicationFile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApplicationFileDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApplicationFileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApplicationFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationFileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ApplicationFiles
   * const applicationFile = await prisma.applicationFile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApplicationFileUpdateManyArgs>(args: Prisma.SelectSubset<T, ApplicationFileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApplicationFiles and returns the data updated in the database.
   * @param {ApplicationFileUpdateManyAndReturnArgs} args - Arguments to update many ApplicationFiles.
   * @example
   * // Update many ApplicationFiles
   * const applicationFile = await prisma.applicationFile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ApplicationFiles and only return the `id`
   * const applicationFileWithIdOnly = await prisma.applicationFile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApplicationFileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApplicationFileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ApplicationFile.
   * @param {ApplicationFileUpsertArgs} args - Arguments to update or create a ApplicationFile.
   * @example
   * // Update or create a ApplicationFile
   * const applicationFile = await prisma.applicationFile.upsert({
   *   create: {
   *     // ... data to create a ApplicationFile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ApplicationFile we want to update
   *   }
   * })
   */
  upsert<T extends ApplicationFileUpsertArgs>(args: Prisma.SelectSubset<T, ApplicationFileUpsertArgs<ExtArgs>>): Prisma.Prisma__ApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$ApplicationFilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ApplicationFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationFileCountArgs} args - Arguments to filter ApplicationFiles to count.
   * @example
   * // Count the number of ApplicationFiles
   * const count = await prisma.applicationFile.count({
   *   where: {
   *     // ... the filter for the ApplicationFiles we want to count
   *   }
   * })
  **/
  count<T extends ApplicationFileCountArgs>(
    args?: Prisma.Subset<T, ApplicationFileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApplicationFileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ApplicationFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationFileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApplicationFileAggregateArgs>(args: Prisma.Subset<T, ApplicationFileAggregateArgs>): Prisma.PrismaPromise<GetApplicationFileAggregateType<T>>

  /**
   * Group by ApplicationFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationFileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApplicationFileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApplicationFileGroupByArgs['orderBy'] }
      : { orderBy?: ApplicationFileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApplicationFileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApplicationFileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ApplicationFile model
 */
readonly fields: ApplicationFileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ApplicationFile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApplicationFileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  application<T extends Prisma.ApplicationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ApplicationDefaultArgs<ExtArgs>>): Prisma.Prisma__ApplicationClient<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ApplicationFile model
 */
export interface ApplicationFileFieldRefs {
  readonly id: Prisma.FieldRef<"ApplicationFile", 'String'>
  readonly applicationId: Prisma.FieldRef<"ApplicationFile", 'String'>
  readonly fieldKey: Prisma.FieldRef<"ApplicationFile", 'String'>
  readonly fileName: Prisma.FieldRef<"ApplicationFile", 'String'>
  readonly fileUrl: Prisma.FieldRef<"ApplicationFile", 'String'>
  readonly mimeType: Prisma.FieldRef<"ApplicationFile", 'String'>
  readonly fileSize: Prisma.FieldRef<"ApplicationFile", 'Int'>
  readonly createdAt: Prisma.FieldRef<"ApplicationFile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ApplicationFile findUnique
 */
export type ApplicationFileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationFile to fetch.
   */
  where: Prisma.ApplicationFileWhereUniqueInput
}

/**
 * ApplicationFile findUniqueOrThrow
 */
export type ApplicationFileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationFile to fetch.
   */
  where: Prisma.ApplicationFileWhereUniqueInput
}

/**
 * ApplicationFile findFirst
 */
export type ApplicationFileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationFile to fetch.
   */
  where?: Prisma.ApplicationFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationFiles to fetch.
   */
  orderBy?: Prisma.ApplicationFileOrderByWithRelationInput | Prisma.ApplicationFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApplicationFiles.
   */
  cursor?: Prisma.ApplicationFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationFiles.
   */
  distinct?: Prisma.ApplicationFileScalarFieldEnum | Prisma.ApplicationFileScalarFieldEnum[]
}

/**
 * ApplicationFile findFirstOrThrow
 */
export type ApplicationFileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationFile to fetch.
   */
  where?: Prisma.ApplicationFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationFiles to fetch.
   */
  orderBy?: Prisma.ApplicationFileOrderByWithRelationInput | Prisma.ApplicationFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApplicationFiles.
   */
  cursor?: Prisma.ApplicationFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationFiles.
   */
  distinct?: Prisma.ApplicationFileScalarFieldEnum | Prisma.ApplicationFileScalarFieldEnum[]
}

/**
 * ApplicationFile findMany
 */
export type ApplicationFileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationFiles to fetch.
   */
  where?: Prisma.ApplicationFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationFiles to fetch.
   */
  orderBy?: Prisma.ApplicationFileOrderByWithRelationInput | Prisma.ApplicationFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ApplicationFiles.
   */
  cursor?: Prisma.ApplicationFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationFiles.
   */
  distinct?: Prisma.ApplicationFileScalarFieldEnum | Prisma.ApplicationFileScalarFieldEnum[]
}

/**
 * ApplicationFile create
 */
export type ApplicationFileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileInclude<ExtArgs> | null
  /**
   * The data needed to create a ApplicationFile.
   */
  data: Prisma.XOR<Prisma.ApplicationFileCreateInput, Prisma.ApplicationFileUncheckedCreateInput>
}

/**
 * ApplicationFile createMany
 */
export type ApplicationFileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ApplicationFiles.
   */
  data: Prisma.ApplicationFileCreateManyInput | Prisma.ApplicationFileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ApplicationFile createManyAndReturn
 */
export type ApplicationFileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * The data used to create many ApplicationFiles.
   */
  data: Prisma.ApplicationFileCreateManyInput | Prisma.ApplicationFileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ApplicationFile update
 */
export type ApplicationFileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileInclude<ExtArgs> | null
  /**
   * The data needed to update a ApplicationFile.
   */
  data: Prisma.XOR<Prisma.ApplicationFileUpdateInput, Prisma.ApplicationFileUncheckedUpdateInput>
  /**
   * Choose, which ApplicationFile to update.
   */
  where: Prisma.ApplicationFileWhereUniqueInput
}

/**
 * ApplicationFile updateMany
 */
export type ApplicationFileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ApplicationFiles.
   */
  data: Prisma.XOR<Prisma.ApplicationFileUpdateManyMutationInput, Prisma.ApplicationFileUncheckedUpdateManyInput>
  /**
   * Filter which ApplicationFiles to update
   */
  where?: Prisma.ApplicationFileWhereInput
  /**
   * Limit how many ApplicationFiles to update.
   */
  limit?: number
}

/**
 * ApplicationFile updateManyAndReturn
 */
export type ApplicationFileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * The data used to update ApplicationFiles.
   */
  data: Prisma.XOR<Prisma.ApplicationFileUpdateManyMutationInput, Prisma.ApplicationFileUncheckedUpdateManyInput>
  /**
   * Filter which ApplicationFiles to update
   */
  where?: Prisma.ApplicationFileWhereInput
  /**
   * Limit how many ApplicationFiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ApplicationFile upsert
 */
export type ApplicationFileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileInclude<ExtArgs> | null
  /**
   * The filter to search for the ApplicationFile to update in case it exists.
   */
  where: Prisma.ApplicationFileWhereUniqueInput
  /**
   * In case the ApplicationFile found by the `where` argument doesn't exist, create a new ApplicationFile with this data.
   */
  create: Prisma.XOR<Prisma.ApplicationFileCreateInput, Prisma.ApplicationFileUncheckedCreateInput>
  /**
   * In case the ApplicationFile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApplicationFileUpdateInput, Prisma.ApplicationFileUncheckedUpdateInput>
}

/**
 * ApplicationFile delete
 */
export type ApplicationFileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileInclude<ExtArgs> | null
  /**
   * Filter which ApplicationFile to delete.
   */
  where: Prisma.ApplicationFileWhereUniqueInput
}

/**
 * ApplicationFile deleteMany
 */
export type ApplicationFileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApplicationFiles to delete
   */
  where?: Prisma.ApplicationFileWhereInput
  /**
   * Limit how many ApplicationFiles to delete.
   */
  limit?: number
}

/**
 * ApplicationFile without action
 */
export type ApplicationFileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationFile
   */
  select?: Prisma.ApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationFile
   */
  omit?: Prisma.ApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationFileInclude<ExtArgs> | null
}
