
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `JuryApplication` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model JuryApplication
 * 
 */
export type JuryApplicationModel = runtime.Types.Result.DefaultSelection<Prisma.$JuryApplicationPayload>

export type AggregateJuryApplication = {
  _count: JuryApplicationCountAggregateOutputType | null
  _avg: JuryApplicationAvgAggregateOutputType | null
  _sum: JuryApplicationSumAggregateOutputType | null
  _min: JuryApplicationMinAggregateOutputType | null
  _max: JuryApplicationMaxAggregateOutputType | null
}

export type JuryApplicationAvgAggregateOutputType = {
  yearsExperience: number | null
  pastWinnerYear: number | null
}

export type JuryApplicationSumAggregateOutputType = {
  yearsExperience: number | null
  pastWinnerYear: number | null
}

export type JuryApplicationMinAggregateOutputType = {
  id: string | null
  fullName: string | null
  email: string | null
  phone: string | null
  country: string | null
  city: string | null
  professionalTitle: string | null
  yearsExperience: number | null
  employerAffiliation: string | null
  membershipStatus: string | null
  membershipLevel: string | null
  previousJudgingExperience: boolean | null
  previousJudgingDetails: string | null
  pastWinner: boolean | null
  pastWinnerYear: number | null
  professionalBio: string | null
  professionalWebsite: string | null
  conflictDisclosure: string | null
  confidentialityAgreementAccepted: boolean | null
  motivation: string | null
  status: $Enums.ApplicationStatus | null
  adminNotes: string | null
  reviewedAt: Date | null
  submittedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type JuryApplicationMaxAggregateOutputType = {
  id: string | null
  fullName: string | null
  email: string | null
  phone: string | null
  country: string | null
  city: string | null
  professionalTitle: string | null
  yearsExperience: number | null
  employerAffiliation: string | null
  membershipStatus: string | null
  membershipLevel: string | null
  previousJudgingExperience: boolean | null
  previousJudgingDetails: string | null
  pastWinner: boolean | null
  pastWinnerYear: number | null
  professionalBio: string | null
  professionalWebsite: string | null
  conflictDisclosure: string | null
  confidentialityAgreementAccepted: boolean | null
  motivation: string | null
  status: $Enums.ApplicationStatus | null
  adminNotes: string | null
  reviewedAt: Date | null
  submittedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type JuryApplicationCountAggregateOutputType = {
  id: number
  fullName: number
  email: number
  phone: number
  country: number
  city: number
  professionalTitle: number
  yearsExperience: number
  employerAffiliation: number
  membershipStatus: number
  membershipLevel: number
  previousJudgingExperience: number
  previousJudgingDetails: number
  pastWinner: number
  pastWinnerYear: number
  expertiseAreas: number
  professionalBio: number
  professionalWebsite: number
  conflictDisclosure: number
  confidentialityAgreementAccepted: number
  motivation: number
  status: number
  adminNotes: number
  reviewedAt: number
  submittedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type JuryApplicationAvgAggregateInputType = {
  yearsExperience?: true
  pastWinnerYear?: true
}

export type JuryApplicationSumAggregateInputType = {
  yearsExperience?: true
  pastWinnerYear?: true
}

export type JuryApplicationMinAggregateInputType = {
  id?: true
  fullName?: true
  email?: true
  phone?: true
  country?: true
  city?: true
  professionalTitle?: true
  yearsExperience?: true
  employerAffiliation?: true
  membershipStatus?: true
  membershipLevel?: true
  previousJudgingExperience?: true
  previousJudgingDetails?: true
  pastWinner?: true
  pastWinnerYear?: true
  professionalBio?: true
  professionalWebsite?: true
  conflictDisclosure?: true
  confidentialityAgreementAccepted?: true
  motivation?: true
  status?: true
  adminNotes?: true
  reviewedAt?: true
  submittedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type JuryApplicationMaxAggregateInputType = {
  id?: true
  fullName?: true
  email?: true
  phone?: true
  country?: true
  city?: true
  professionalTitle?: true
  yearsExperience?: true
  employerAffiliation?: true
  membershipStatus?: true
  membershipLevel?: true
  previousJudgingExperience?: true
  previousJudgingDetails?: true
  pastWinner?: true
  pastWinnerYear?: true
  professionalBio?: true
  professionalWebsite?: true
  conflictDisclosure?: true
  confidentialityAgreementAccepted?: true
  motivation?: true
  status?: true
  adminNotes?: true
  reviewedAt?: true
  submittedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type JuryApplicationCountAggregateInputType = {
  id?: true
  fullName?: true
  email?: true
  phone?: true
  country?: true
  city?: true
  professionalTitle?: true
  yearsExperience?: true
  employerAffiliation?: true
  membershipStatus?: true
  membershipLevel?: true
  previousJudgingExperience?: true
  previousJudgingDetails?: true
  pastWinner?: true
  pastWinnerYear?: true
  expertiseAreas?: true
  professionalBio?: true
  professionalWebsite?: true
  conflictDisclosure?: true
  confidentialityAgreementAccepted?: true
  motivation?: true
  status?: true
  adminNotes?: true
  reviewedAt?: true
  submittedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type JuryApplicationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JuryApplication to aggregate.
   */
  where?: Prisma.JuryApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JuryApplications to fetch.
   */
  orderBy?: Prisma.JuryApplicationOrderByWithRelationInput | Prisma.JuryApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.JuryApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JuryApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JuryApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned JuryApplications
  **/
  _count?: true | JuryApplicationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: JuryApplicationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: JuryApplicationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: JuryApplicationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: JuryApplicationMaxAggregateInputType
}

export type GetJuryApplicationAggregateType<T extends JuryApplicationAggregateArgs> = {
      [P in keyof T & keyof AggregateJuryApplication]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateJuryApplication[P]>
    : Prisma.GetScalarType<T[P], AggregateJuryApplication[P]>
}




export type JuryApplicationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JuryApplicationWhereInput
  orderBy?: Prisma.JuryApplicationOrderByWithAggregationInput | Prisma.JuryApplicationOrderByWithAggregationInput[]
  by: Prisma.JuryApplicationScalarFieldEnum[] | Prisma.JuryApplicationScalarFieldEnum
  having?: Prisma.JuryApplicationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: JuryApplicationCountAggregateInputType | true
  _avg?: JuryApplicationAvgAggregateInputType
  _sum?: JuryApplicationSumAggregateInputType
  _min?: JuryApplicationMinAggregateInputType
  _max?: JuryApplicationMaxAggregateInputType
}

export type JuryApplicationGroupByOutputType = {
  id: string
  fullName: string
  email: string
  phone: string
  country: string
  city: string
  professionalTitle: string
  yearsExperience: number
  employerAffiliation: string
  membershipStatus: string
  membershipLevel: string | null
  previousJudgingExperience: boolean
  previousJudgingDetails: string | null
  pastWinner: boolean
  pastWinnerYear: number | null
  expertiseAreas: string[]
  professionalBio: string
  professionalWebsite: string | null
  conflictDisclosure: string
  confidentialityAgreementAccepted: boolean
  motivation: string
  status: $Enums.ApplicationStatus
  adminNotes: string | null
  reviewedAt: Date | null
  submittedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: JuryApplicationCountAggregateOutputType | null
  _avg: JuryApplicationAvgAggregateOutputType | null
  _sum: JuryApplicationSumAggregateOutputType | null
  _min: JuryApplicationMinAggregateOutputType | null
  _max: JuryApplicationMaxAggregateOutputType | null
}

export type GetJuryApplicationGroupByPayload<T extends JuryApplicationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<JuryApplicationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof JuryApplicationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], JuryApplicationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], JuryApplicationGroupByOutputType[P]>
      }
    >
  >



export type JuryApplicationWhereInput = {
  AND?: Prisma.JuryApplicationWhereInput | Prisma.JuryApplicationWhereInput[]
  OR?: Prisma.JuryApplicationWhereInput[]
  NOT?: Prisma.JuryApplicationWhereInput | Prisma.JuryApplicationWhereInput[]
  id?: Prisma.StringFilter<"JuryApplication"> | string
  fullName?: Prisma.StringFilter<"JuryApplication"> | string
  email?: Prisma.StringFilter<"JuryApplication"> | string
  phone?: Prisma.StringFilter<"JuryApplication"> | string
  country?: Prisma.StringFilter<"JuryApplication"> | string
  city?: Prisma.StringFilter<"JuryApplication"> | string
  professionalTitle?: Prisma.StringFilter<"JuryApplication"> | string
  yearsExperience?: Prisma.IntFilter<"JuryApplication"> | number
  employerAffiliation?: Prisma.StringFilter<"JuryApplication"> | string
  membershipStatus?: Prisma.StringFilter<"JuryApplication"> | string
  membershipLevel?: Prisma.StringNullableFilter<"JuryApplication"> | string | null
  previousJudgingExperience?: Prisma.BoolFilter<"JuryApplication"> | boolean
  previousJudgingDetails?: Prisma.StringNullableFilter<"JuryApplication"> | string | null
  pastWinner?: Prisma.BoolFilter<"JuryApplication"> | boolean
  pastWinnerYear?: Prisma.IntNullableFilter<"JuryApplication"> | number | null
  expertiseAreas?: Prisma.StringNullableListFilter<"JuryApplication">
  professionalBio?: Prisma.StringFilter<"JuryApplication"> | string
  professionalWebsite?: Prisma.StringNullableFilter<"JuryApplication"> | string | null
  conflictDisclosure?: Prisma.StringFilter<"JuryApplication"> | string
  confidentialityAgreementAccepted?: Prisma.BoolFilter<"JuryApplication"> | boolean
  motivation?: Prisma.StringFilter<"JuryApplication"> | string
  status?: Prisma.EnumApplicationStatusFilter<"JuryApplication"> | $Enums.ApplicationStatus
  adminNotes?: Prisma.StringNullableFilter<"JuryApplication"> | string | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"JuryApplication"> | Date | string | null
  submittedAt?: Prisma.DateTimeNullableFilter<"JuryApplication"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"JuryApplication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"JuryApplication"> | Date | string
  files?: Prisma.JuryApplicationFileListRelationFilter
}

export type JuryApplicationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  country?: Prisma.SortOrder
  city?: Prisma.SortOrder
  professionalTitle?: Prisma.SortOrder
  yearsExperience?: Prisma.SortOrder
  employerAffiliation?: Prisma.SortOrder
  membershipStatus?: Prisma.SortOrder
  membershipLevel?: Prisma.SortOrderInput | Prisma.SortOrder
  previousJudgingExperience?: Prisma.SortOrder
  previousJudgingDetails?: Prisma.SortOrderInput | Prisma.SortOrder
  pastWinner?: Prisma.SortOrder
  pastWinnerYear?: Prisma.SortOrderInput | Prisma.SortOrder
  expertiseAreas?: Prisma.SortOrder
  professionalBio?: Prisma.SortOrder
  professionalWebsite?: Prisma.SortOrderInput | Prisma.SortOrder
  conflictDisclosure?: Prisma.SortOrder
  confidentialityAgreementAccepted?: Prisma.SortOrder
  motivation?: Prisma.SortOrder
  status?: Prisma.SortOrder
  adminNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  files?: Prisma.JuryApplicationFileOrderByRelationAggregateInput
}

export type JuryApplicationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.JuryApplicationWhereInput | Prisma.JuryApplicationWhereInput[]
  OR?: Prisma.JuryApplicationWhereInput[]
  NOT?: Prisma.JuryApplicationWhereInput | Prisma.JuryApplicationWhereInput[]
  fullName?: Prisma.StringFilter<"JuryApplication"> | string
  email?: Prisma.StringFilter<"JuryApplication"> | string
  phone?: Prisma.StringFilter<"JuryApplication"> | string
  country?: Prisma.StringFilter<"JuryApplication"> | string
  city?: Prisma.StringFilter<"JuryApplication"> | string
  professionalTitle?: Prisma.StringFilter<"JuryApplication"> | string
  yearsExperience?: Prisma.IntFilter<"JuryApplication"> | number
  employerAffiliation?: Prisma.StringFilter<"JuryApplication"> | string
  membershipStatus?: Prisma.StringFilter<"JuryApplication"> | string
  membershipLevel?: Prisma.StringNullableFilter<"JuryApplication"> | string | null
  previousJudgingExperience?: Prisma.BoolFilter<"JuryApplication"> | boolean
  previousJudgingDetails?: Prisma.StringNullableFilter<"JuryApplication"> | string | null
  pastWinner?: Prisma.BoolFilter<"JuryApplication"> | boolean
  pastWinnerYear?: Prisma.IntNullableFilter<"JuryApplication"> | number | null
  expertiseAreas?: Prisma.StringNullableListFilter<"JuryApplication">
  professionalBio?: Prisma.StringFilter<"JuryApplication"> | string
  professionalWebsite?: Prisma.StringNullableFilter<"JuryApplication"> | string | null
  conflictDisclosure?: Prisma.StringFilter<"JuryApplication"> | string
  confidentialityAgreementAccepted?: Prisma.BoolFilter<"JuryApplication"> | boolean
  motivation?: Prisma.StringFilter<"JuryApplication"> | string
  status?: Prisma.EnumApplicationStatusFilter<"JuryApplication"> | $Enums.ApplicationStatus
  adminNotes?: Prisma.StringNullableFilter<"JuryApplication"> | string | null
  reviewedAt?: Prisma.DateTimeNullableFilter<"JuryApplication"> | Date | string | null
  submittedAt?: Prisma.DateTimeNullableFilter<"JuryApplication"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"JuryApplication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"JuryApplication"> | Date | string
  files?: Prisma.JuryApplicationFileListRelationFilter
}, "id">

export type JuryApplicationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  country?: Prisma.SortOrder
  city?: Prisma.SortOrder
  professionalTitle?: Prisma.SortOrder
  yearsExperience?: Prisma.SortOrder
  employerAffiliation?: Prisma.SortOrder
  membershipStatus?: Prisma.SortOrder
  membershipLevel?: Prisma.SortOrderInput | Prisma.SortOrder
  previousJudgingExperience?: Prisma.SortOrder
  previousJudgingDetails?: Prisma.SortOrderInput | Prisma.SortOrder
  pastWinner?: Prisma.SortOrder
  pastWinnerYear?: Prisma.SortOrderInput | Prisma.SortOrder
  expertiseAreas?: Prisma.SortOrder
  professionalBio?: Prisma.SortOrder
  professionalWebsite?: Prisma.SortOrderInput | Prisma.SortOrder
  conflictDisclosure?: Prisma.SortOrder
  confidentialityAgreementAccepted?: Prisma.SortOrder
  motivation?: Prisma.SortOrder
  status?: Prisma.SortOrder
  adminNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.JuryApplicationCountOrderByAggregateInput
  _avg?: Prisma.JuryApplicationAvgOrderByAggregateInput
  _max?: Prisma.JuryApplicationMaxOrderByAggregateInput
  _min?: Prisma.JuryApplicationMinOrderByAggregateInput
  _sum?: Prisma.JuryApplicationSumOrderByAggregateInput
}

export type JuryApplicationScalarWhereWithAggregatesInput = {
  AND?: Prisma.JuryApplicationScalarWhereWithAggregatesInput | Prisma.JuryApplicationScalarWhereWithAggregatesInput[]
  OR?: Prisma.JuryApplicationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.JuryApplicationScalarWhereWithAggregatesInput | Prisma.JuryApplicationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  fullName?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  email?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  phone?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  country?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  city?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  professionalTitle?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  yearsExperience?: Prisma.IntWithAggregatesFilter<"JuryApplication"> | number
  employerAffiliation?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  membershipStatus?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  membershipLevel?: Prisma.StringNullableWithAggregatesFilter<"JuryApplication"> | string | null
  previousJudgingExperience?: Prisma.BoolWithAggregatesFilter<"JuryApplication"> | boolean
  previousJudgingDetails?: Prisma.StringNullableWithAggregatesFilter<"JuryApplication"> | string | null
  pastWinner?: Prisma.BoolWithAggregatesFilter<"JuryApplication"> | boolean
  pastWinnerYear?: Prisma.IntNullableWithAggregatesFilter<"JuryApplication"> | number | null
  expertiseAreas?: Prisma.StringNullableListFilter<"JuryApplication">
  professionalBio?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  professionalWebsite?: Prisma.StringNullableWithAggregatesFilter<"JuryApplication"> | string | null
  conflictDisclosure?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  confidentialityAgreementAccepted?: Prisma.BoolWithAggregatesFilter<"JuryApplication"> | boolean
  motivation?: Prisma.StringWithAggregatesFilter<"JuryApplication"> | string
  status?: Prisma.EnumApplicationStatusWithAggregatesFilter<"JuryApplication"> | $Enums.ApplicationStatus
  adminNotes?: Prisma.StringNullableWithAggregatesFilter<"JuryApplication"> | string | null
  reviewedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"JuryApplication"> | Date | string | null
  submittedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"JuryApplication"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"JuryApplication"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"JuryApplication"> | Date | string
}

export type JuryApplicationCreateInput = {
  id?: string
  fullName: string
  email: string
  phone: string
  country: string
  city: string
  professionalTitle: string
  yearsExperience: number
  employerAffiliation: string
  membershipStatus: string
  membershipLevel?: string | null
  previousJudgingExperience: boolean
  previousJudgingDetails?: string | null
  pastWinner?: boolean
  pastWinnerYear?: number | null
  expertiseAreas?: Prisma.JuryApplicationCreateexpertiseAreasInput | string[]
  professionalBio: string
  professionalWebsite?: string | null
  conflictDisclosure: string
  confidentialityAgreementAccepted?: boolean
  motivation: string
  status?: $Enums.ApplicationStatus
  adminNotes?: string | null
  reviewedAt?: Date | string | null
  submittedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  files?: Prisma.JuryApplicationFileCreateNestedManyWithoutJuryApplicationInput
}

export type JuryApplicationUncheckedCreateInput = {
  id?: string
  fullName: string
  email: string
  phone: string
  country: string
  city: string
  professionalTitle: string
  yearsExperience: number
  employerAffiliation: string
  membershipStatus: string
  membershipLevel?: string | null
  previousJudgingExperience: boolean
  previousJudgingDetails?: string | null
  pastWinner?: boolean
  pastWinnerYear?: number | null
  expertiseAreas?: Prisma.JuryApplicationCreateexpertiseAreasInput | string[]
  professionalBio: string
  professionalWebsite?: string | null
  conflictDisclosure: string
  confidentialityAgreementAccepted?: boolean
  motivation: string
  status?: $Enums.ApplicationStatus
  adminNotes?: string | null
  reviewedAt?: Date | string | null
  submittedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  files?: Prisma.JuryApplicationFileUncheckedCreateNestedManyWithoutJuryApplicationInput
}

export type JuryApplicationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  professionalTitle?: Prisma.StringFieldUpdateOperationsInput | string
  yearsExperience?: Prisma.IntFieldUpdateOperationsInput | number
  employerAffiliation?: Prisma.StringFieldUpdateOperationsInput | string
  membershipStatus?: Prisma.StringFieldUpdateOperationsInput | string
  membershipLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  previousJudgingExperience?: Prisma.BoolFieldUpdateOperationsInput | boolean
  previousJudgingDetails?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pastWinner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  pastWinnerYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  expertiseAreas?: Prisma.JuryApplicationUpdateexpertiseAreasInput | string[]
  professionalBio?: Prisma.StringFieldUpdateOperationsInput | string
  professionalWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conflictDisclosure?: Prisma.StringFieldUpdateOperationsInput | string
  confidentialityAgreementAccepted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  motivation?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  files?: Prisma.JuryApplicationFileUpdateManyWithoutJuryApplicationNestedInput
}

export type JuryApplicationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  professionalTitle?: Prisma.StringFieldUpdateOperationsInput | string
  yearsExperience?: Prisma.IntFieldUpdateOperationsInput | number
  employerAffiliation?: Prisma.StringFieldUpdateOperationsInput | string
  membershipStatus?: Prisma.StringFieldUpdateOperationsInput | string
  membershipLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  previousJudgingExperience?: Prisma.BoolFieldUpdateOperationsInput | boolean
  previousJudgingDetails?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pastWinner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  pastWinnerYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  expertiseAreas?: Prisma.JuryApplicationUpdateexpertiseAreasInput | string[]
  professionalBio?: Prisma.StringFieldUpdateOperationsInput | string
  professionalWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conflictDisclosure?: Prisma.StringFieldUpdateOperationsInput | string
  confidentialityAgreementAccepted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  motivation?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  files?: Prisma.JuryApplicationFileUncheckedUpdateManyWithoutJuryApplicationNestedInput
}

export type JuryApplicationCreateManyInput = {
  id?: string
  fullName: string
  email: string
  phone: string
  country: string
  city: string
  professionalTitle: string
  yearsExperience: number
  employerAffiliation: string
  membershipStatus: string
  membershipLevel?: string | null
  previousJudgingExperience: boolean
  previousJudgingDetails?: string | null
  pastWinner?: boolean
  pastWinnerYear?: number | null
  expertiseAreas?: Prisma.JuryApplicationCreateexpertiseAreasInput | string[]
  professionalBio: string
  professionalWebsite?: string | null
  conflictDisclosure: string
  confidentialityAgreementAccepted?: boolean
  motivation: string
  status?: $Enums.ApplicationStatus
  adminNotes?: string | null
  reviewedAt?: Date | string | null
  submittedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JuryApplicationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  professionalTitle?: Prisma.StringFieldUpdateOperationsInput | string
  yearsExperience?: Prisma.IntFieldUpdateOperationsInput | number
  employerAffiliation?: Prisma.StringFieldUpdateOperationsInput | string
  membershipStatus?: Prisma.StringFieldUpdateOperationsInput | string
  membershipLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  previousJudgingExperience?: Prisma.BoolFieldUpdateOperationsInput | boolean
  previousJudgingDetails?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pastWinner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  pastWinnerYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  expertiseAreas?: Prisma.JuryApplicationUpdateexpertiseAreasInput | string[]
  professionalBio?: Prisma.StringFieldUpdateOperationsInput | string
  professionalWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conflictDisclosure?: Prisma.StringFieldUpdateOperationsInput | string
  confidentialityAgreementAccepted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  motivation?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JuryApplicationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  professionalTitle?: Prisma.StringFieldUpdateOperationsInput | string
  yearsExperience?: Prisma.IntFieldUpdateOperationsInput | number
  employerAffiliation?: Prisma.StringFieldUpdateOperationsInput | string
  membershipStatus?: Prisma.StringFieldUpdateOperationsInput | string
  membershipLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  previousJudgingExperience?: Prisma.BoolFieldUpdateOperationsInput | boolean
  previousJudgingDetails?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pastWinner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  pastWinnerYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  expertiseAreas?: Prisma.JuryApplicationUpdateexpertiseAreasInput | string[]
  professionalBio?: Prisma.StringFieldUpdateOperationsInput | string
  professionalWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conflictDisclosure?: Prisma.StringFieldUpdateOperationsInput | string
  confidentialityAgreementAccepted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  motivation?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type JuryApplicationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  country?: Prisma.SortOrder
  city?: Prisma.SortOrder
  professionalTitle?: Prisma.SortOrder
  yearsExperience?: Prisma.SortOrder
  employerAffiliation?: Prisma.SortOrder
  membershipStatus?: Prisma.SortOrder
  membershipLevel?: Prisma.SortOrder
  previousJudgingExperience?: Prisma.SortOrder
  previousJudgingDetails?: Prisma.SortOrder
  pastWinner?: Prisma.SortOrder
  pastWinnerYear?: Prisma.SortOrder
  expertiseAreas?: Prisma.SortOrder
  professionalBio?: Prisma.SortOrder
  professionalWebsite?: Prisma.SortOrder
  conflictDisclosure?: Prisma.SortOrder
  confidentialityAgreementAccepted?: Prisma.SortOrder
  motivation?: Prisma.SortOrder
  status?: Prisma.SortOrder
  adminNotes?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JuryApplicationAvgOrderByAggregateInput = {
  yearsExperience?: Prisma.SortOrder
  pastWinnerYear?: Prisma.SortOrder
}

export type JuryApplicationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  country?: Prisma.SortOrder
  city?: Prisma.SortOrder
  professionalTitle?: Prisma.SortOrder
  yearsExperience?: Prisma.SortOrder
  employerAffiliation?: Prisma.SortOrder
  membershipStatus?: Prisma.SortOrder
  membershipLevel?: Prisma.SortOrder
  previousJudgingExperience?: Prisma.SortOrder
  previousJudgingDetails?: Prisma.SortOrder
  pastWinner?: Prisma.SortOrder
  pastWinnerYear?: Prisma.SortOrder
  professionalBio?: Prisma.SortOrder
  professionalWebsite?: Prisma.SortOrder
  conflictDisclosure?: Prisma.SortOrder
  confidentialityAgreementAccepted?: Prisma.SortOrder
  motivation?: Prisma.SortOrder
  status?: Prisma.SortOrder
  adminNotes?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JuryApplicationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  country?: Prisma.SortOrder
  city?: Prisma.SortOrder
  professionalTitle?: Prisma.SortOrder
  yearsExperience?: Prisma.SortOrder
  employerAffiliation?: Prisma.SortOrder
  membershipStatus?: Prisma.SortOrder
  membershipLevel?: Prisma.SortOrder
  previousJudgingExperience?: Prisma.SortOrder
  previousJudgingDetails?: Prisma.SortOrder
  pastWinner?: Prisma.SortOrder
  pastWinnerYear?: Prisma.SortOrder
  professionalBio?: Prisma.SortOrder
  professionalWebsite?: Prisma.SortOrder
  conflictDisclosure?: Prisma.SortOrder
  confidentialityAgreementAccepted?: Prisma.SortOrder
  motivation?: Prisma.SortOrder
  status?: Prisma.SortOrder
  adminNotes?: Prisma.SortOrder
  reviewedAt?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JuryApplicationSumOrderByAggregateInput = {
  yearsExperience?: Prisma.SortOrder
  pastWinnerYear?: Prisma.SortOrder
}

export type JuryApplicationScalarRelationFilter = {
  is?: Prisma.JuryApplicationWhereInput
  isNot?: Prisma.JuryApplicationWhereInput
}

export type JuryApplicationCreateexpertiseAreasInput = {
  set: string[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type JuryApplicationUpdateexpertiseAreasInput = {
  set?: string[]
  push?: string | string[]
}

export type JuryApplicationCreateNestedOneWithoutFilesInput = {
  create?: Prisma.XOR<Prisma.JuryApplicationCreateWithoutFilesInput, Prisma.JuryApplicationUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.JuryApplicationCreateOrConnectWithoutFilesInput
  connect?: Prisma.JuryApplicationWhereUniqueInput
}

export type JuryApplicationUpdateOneRequiredWithoutFilesNestedInput = {
  create?: Prisma.XOR<Prisma.JuryApplicationCreateWithoutFilesInput, Prisma.JuryApplicationUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.JuryApplicationCreateOrConnectWithoutFilesInput
  upsert?: Prisma.JuryApplicationUpsertWithoutFilesInput
  connect?: Prisma.JuryApplicationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.JuryApplicationUpdateToOneWithWhereWithoutFilesInput, Prisma.JuryApplicationUpdateWithoutFilesInput>, Prisma.JuryApplicationUncheckedUpdateWithoutFilesInput>
}

export type JuryApplicationCreateWithoutFilesInput = {
  id?: string
  fullName: string
  email: string
  phone: string
  country: string
  city: string
  professionalTitle: string
  yearsExperience: number
  employerAffiliation: string
  membershipStatus: string
  membershipLevel?: string | null
  previousJudgingExperience: boolean
  previousJudgingDetails?: string | null
  pastWinner?: boolean
  pastWinnerYear?: number | null
  expertiseAreas?: Prisma.JuryApplicationCreateexpertiseAreasInput | string[]
  professionalBio: string
  professionalWebsite?: string | null
  conflictDisclosure: string
  confidentialityAgreementAccepted?: boolean
  motivation: string
  status?: $Enums.ApplicationStatus
  adminNotes?: string | null
  reviewedAt?: Date | string | null
  submittedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JuryApplicationUncheckedCreateWithoutFilesInput = {
  id?: string
  fullName: string
  email: string
  phone: string
  country: string
  city: string
  professionalTitle: string
  yearsExperience: number
  employerAffiliation: string
  membershipStatus: string
  membershipLevel?: string | null
  previousJudgingExperience: boolean
  previousJudgingDetails?: string | null
  pastWinner?: boolean
  pastWinnerYear?: number | null
  expertiseAreas?: Prisma.JuryApplicationCreateexpertiseAreasInput | string[]
  professionalBio: string
  professionalWebsite?: string | null
  conflictDisclosure: string
  confidentialityAgreementAccepted?: boolean
  motivation: string
  status?: $Enums.ApplicationStatus
  adminNotes?: string | null
  reviewedAt?: Date | string | null
  submittedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JuryApplicationCreateOrConnectWithoutFilesInput = {
  where: Prisma.JuryApplicationWhereUniqueInput
  create: Prisma.XOR<Prisma.JuryApplicationCreateWithoutFilesInput, Prisma.JuryApplicationUncheckedCreateWithoutFilesInput>
}

export type JuryApplicationUpsertWithoutFilesInput = {
  update: Prisma.XOR<Prisma.JuryApplicationUpdateWithoutFilesInput, Prisma.JuryApplicationUncheckedUpdateWithoutFilesInput>
  create: Prisma.XOR<Prisma.JuryApplicationCreateWithoutFilesInput, Prisma.JuryApplicationUncheckedCreateWithoutFilesInput>
  where?: Prisma.JuryApplicationWhereInput
}

export type JuryApplicationUpdateToOneWithWhereWithoutFilesInput = {
  where?: Prisma.JuryApplicationWhereInput
  data: Prisma.XOR<Prisma.JuryApplicationUpdateWithoutFilesInput, Prisma.JuryApplicationUncheckedUpdateWithoutFilesInput>
}

export type JuryApplicationUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  professionalTitle?: Prisma.StringFieldUpdateOperationsInput | string
  yearsExperience?: Prisma.IntFieldUpdateOperationsInput | number
  employerAffiliation?: Prisma.StringFieldUpdateOperationsInput | string
  membershipStatus?: Prisma.StringFieldUpdateOperationsInput | string
  membershipLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  previousJudgingExperience?: Prisma.BoolFieldUpdateOperationsInput | boolean
  previousJudgingDetails?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pastWinner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  pastWinnerYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  expertiseAreas?: Prisma.JuryApplicationUpdateexpertiseAreasInput | string[]
  professionalBio?: Prisma.StringFieldUpdateOperationsInput | string
  professionalWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conflictDisclosure?: Prisma.StringFieldUpdateOperationsInput | string
  confidentialityAgreementAccepted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  motivation?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JuryApplicationUncheckedUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  professionalTitle?: Prisma.StringFieldUpdateOperationsInput | string
  yearsExperience?: Prisma.IntFieldUpdateOperationsInput | number
  employerAffiliation?: Prisma.StringFieldUpdateOperationsInput | string
  membershipStatus?: Prisma.StringFieldUpdateOperationsInput | string
  membershipLevel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  previousJudgingExperience?: Prisma.BoolFieldUpdateOperationsInput | boolean
  previousJudgingDetails?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pastWinner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  pastWinnerYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  expertiseAreas?: Prisma.JuryApplicationUpdateexpertiseAreasInput | string[]
  professionalBio?: Prisma.StringFieldUpdateOperationsInput | string
  professionalWebsite?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conflictDisclosure?: Prisma.StringFieldUpdateOperationsInput | string
  confidentialityAgreementAccepted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  motivation?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumApplicationStatusFieldUpdateOperationsInput | $Enums.ApplicationStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type JuryApplicationCountOutputType
 */

export type JuryApplicationCountOutputType = {
  files: number
}

export type JuryApplicationCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  files?: boolean | JuryApplicationCountOutputTypeCountFilesArgs
}

/**
 * JuryApplicationCountOutputType without action
 */
export type JuryApplicationCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationCountOutputType
   */
  select?: Prisma.JuryApplicationCountOutputTypeSelect<ExtArgs> | null
}

/**
 * JuryApplicationCountOutputType without action
 */
export type JuryApplicationCountOutputTypeCountFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JuryApplicationFileWhereInput
}


export type JuryApplicationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  email?: boolean
  phone?: boolean
  country?: boolean
  city?: boolean
  professionalTitle?: boolean
  yearsExperience?: boolean
  employerAffiliation?: boolean
  membershipStatus?: boolean
  membershipLevel?: boolean
  previousJudgingExperience?: boolean
  previousJudgingDetails?: boolean
  pastWinner?: boolean
  pastWinnerYear?: boolean
  expertiseAreas?: boolean
  professionalBio?: boolean
  professionalWebsite?: boolean
  conflictDisclosure?: boolean
  confidentialityAgreementAccepted?: boolean
  motivation?: boolean
  status?: boolean
  adminNotes?: boolean
  reviewedAt?: boolean
  submittedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  files?: boolean | Prisma.JuryApplication$filesArgs<ExtArgs>
  _count?: boolean | Prisma.JuryApplicationCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["juryApplication"]>

export type JuryApplicationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  email?: boolean
  phone?: boolean
  country?: boolean
  city?: boolean
  professionalTitle?: boolean
  yearsExperience?: boolean
  employerAffiliation?: boolean
  membershipStatus?: boolean
  membershipLevel?: boolean
  previousJudgingExperience?: boolean
  previousJudgingDetails?: boolean
  pastWinner?: boolean
  pastWinnerYear?: boolean
  expertiseAreas?: boolean
  professionalBio?: boolean
  professionalWebsite?: boolean
  conflictDisclosure?: boolean
  confidentialityAgreementAccepted?: boolean
  motivation?: boolean
  status?: boolean
  adminNotes?: boolean
  reviewedAt?: boolean
  submittedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["juryApplication"]>

export type JuryApplicationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  email?: boolean
  phone?: boolean
  country?: boolean
  city?: boolean
  professionalTitle?: boolean
  yearsExperience?: boolean
  employerAffiliation?: boolean
  membershipStatus?: boolean
  membershipLevel?: boolean
  previousJudgingExperience?: boolean
  previousJudgingDetails?: boolean
  pastWinner?: boolean
  pastWinnerYear?: boolean
  expertiseAreas?: boolean
  professionalBio?: boolean
  professionalWebsite?: boolean
  conflictDisclosure?: boolean
  confidentialityAgreementAccepted?: boolean
  motivation?: boolean
  status?: boolean
  adminNotes?: boolean
  reviewedAt?: boolean
  submittedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["juryApplication"]>

export type JuryApplicationSelectScalar = {
  id?: boolean
  fullName?: boolean
  email?: boolean
  phone?: boolean
  country?: boolean
  city?: boolean
  professionalTitle?: boolean
  yearsExperience?: boolean
  employerAffiliation?: boolean
  membershipStatus?: boolean
  membershipLevel?: boolean
  previousJudgingExperience?: boolean
  previousJudgingDetails?: boolean
  pastWinner?: boolean
  pastWinnerYear?: boolean
  expertiseAreas?: boolean
  professionalBio?: boolean
  professionalWebsite?: boolean
  conflictDisclosure?: boolean
  confidentialityAgreementAccepted?: boolean
  motivation?: boolean
  status?: boolean
  adminNotes?: boolean
  reviewedAt?: boolean
  submittedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type JuryApplicationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fullName" | "email" | "phone" | "country" | "city" | "professionalTitle" | "yearsExperience" | "employerAffiliation" | "membershipStatus" | "membershipLevel" | "previousJudgingExperience" | "previousJudgingDetails" | "pastWinner" | "pastWinnerYear" | "expertiseAreas" | "professionalBio" | "professionalWebsite" | "conflictDisclosure" | "confidentialityAgreementAccepted" | "motivation" | "status" | "adminNotes" | "reviewedAt" | "submittedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["juryApplication"]>
export type JuryApplicationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  files?: boolean | Prisma.JuryApplication$filesArgs<ExtArgs>
  _count?: boolean | Prisma.JuryApplicationCountOutputTypeDefaultArgs<ExtArgs>
}
export type JuryApplicationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type JuryApplicationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $JuryApplicationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "JuryApplication"
  objects: {
    files: Prisma.$JuryApplicationFilePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fullName: string
    email: string
    phone: string
    country: string
    city: string
    professionalTitle: string
    yearsExperience: number
    employerAffiliation: string
    membershipStatus: string
    membershipLevel: string | null
    previousJudgingExperience: boolean
    previousJudgingDetails: string | null
    pastWinner: boolean
    pastWinnerYear: number | null
    expertiseAreas: string[]
    professionalBio: string
    professionalWebsite: string | null
    conflictDisclosure: string
    confidentialityAgreementAccepted: boolean
    motivation: string
    status: $Enums.ApplicationStatus
    adminNotes: string | null
    reviewedAt: Date | null
    submittedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["juryApplication"]>
  composites: {}
}

export type JuryApplicationGetPayload<S extends boolean | null | undefined | JuryApplicationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload, S>

export type JuryApplicationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<JuryApplicationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: JuryApplicationCountAggregateInputType | true
  }

export interface JuryApplicationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['JuryApplication'], meta: { name: 'JuryApplication' } }
  /**
   * Find zero or one JuryApplication that matches the filter.
   * @param {JuryApplicationFindUniqueArgs} args - Arguments to find a JuryApplication
   * @example
   * // Get one JuryApplication
   * const juryApplication = await prisma.juryApplication.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends JuryApplicationFindUniqueArgs>(args: Prisma.SelectSubset<T, JuryApplicationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one JuryApplication that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {JuryApplicationFindUniqueOrThrowArgs} args - Arguments to find a JuryApplication
   * @example
   * // Get one JuryApplication
   * const juryApplication = await prisma.juryApplication.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends JuryApplicationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, JuryApplicationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JuryApplication that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationFindFirstArgs} args - Arguments to find a JuryApplication
   * @example
   * // Get one JuryApplication
   * const juryApplication = await prisma.juryApplication.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends JuryApplicationFindFirstArgs>(args?: Prisma.SelectSubset<T, JuryApplicationFindFirstArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JuryApplication that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationFindFirstOrThrowArgs} args - Arguments to find a JuryApplication
   * @example
   * // Get one JuryApplication
   * const juryApplication = await prisma.juryApplication.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends JuryApplicationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, JuryApplicationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more JuryApplications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all JuryApplications
   * const juryApplications = await prisma.juryApplication.findMany()
   * 
   * // Get first 10 JuryApplications
   * const juryApplications = await prisma.juryApplication.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const juryApplicationWithIdOnly = await prisma.juryApplication.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends JuryApplicationFindManyArgs>(args?: Prisma.SelectSubset<T, JuryApplicationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a JuryApplication.
   * @param {JuryApplicationCreateArgs} args - Arguments to create a JuryApplication.
   * @example
   * // Create one JuryApplication
   * const JuryApplication = await prisma.juryApplication.create({
   *   data: {
   *     // ... data to create a JuryApplication
   *   }
   * })
   * 
   */
  create<T extends JuryApplicationCreateArgs>(args: Prisma.SelectSubset<T, JuryApplicationCreateArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many JuryApplications.
   * @param {JuryApplicationCreateManyArgs} args - Arguments to create many JuryApplications.
   * @example
   * // Create many JuryApplications
   * const juryApplication = await prisma.juryApplication.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends JuryApplicationCreateManyArgs>(args?: Prisma.SelectSubset<T, JuryApplicationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many JuryApplications and returns the data saved in the database.
   * @param {JuryApplicationCreateManyAndReturnArgs} args - Arguments to create many JuryApplications.
   * @example
   * // Create many JuryApplications
   * const juryApplication = await prisma.juryApplication.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many JuryApplications and only return the `id`
   * const juryApplicationWithIdOnly = await prisma.juryApplication.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends JuryApplicationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, JuryApplicationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a JuryApplication.
   * @param {JuryApplicationDeleteArgs} args - Arguments to delete one JuryApplication.
   * @example
   * // Delete one JuryApplication
   * const JuryApplication = await prisma.juryApplication.delete({
   *   where: {
   *     // ... filter to delete one JuryApplication
   *   }
   * })
   * 
   */
  delete<T extends JuryApplicationDeleteArgs>(args: Prisma.SelectSubset<T, JuryApplicationDeleteArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one JuryApplication.
   * @param {JuryApplicationUpdateArgs} args - Arguments to update one JuryApplication.
   * @example
   * // Update one JuryApplication
   * const juryApplication = await prisma.juryApplication.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends JuryApplicationUpdateArgs>(args: Prisma.SelectSubset<T, JuryApplicationUpdateArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more JuryApplications.
   * @param {JuryApplicationDeleteManyArgs} args - Arguments to filter JuryApplications to delete.
   * @example
   * // Delete a few JuryApplications
   * const { count } = await prisma.juryApplication.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends JuryApplicationDeleteManyArgs>(args?: Prisma.SelectSubset<T, JuryApplicationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JuryApplications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many JuryApplications
   * const juryApplication = await prisma.juryApplication.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends JuryApplicationUpdateManyArgs>(args: Prisma.SelectSubset<T, JuryApplicationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JuryApplications and returns the data updated in the database.
   * @param {JuryApplicationUpdateManyAndReturnArgs} args - Arguments to update many JuryApplications.
   * @example
   * // Update many JuryApplications
   * const juryApplication = await prisma.juryApplication.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more JuryApplications and only return the `id`
   * const juryApplicationWithIdOnly = await prisma.juryApplication.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends JuryApplicationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, JuryApplicationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one JuryApplication.
   * @param {JuryApplicationUpsertArgs} args - Arguments to update or create a JuryApplication.
   * @example
   * // Update or create a JuryApplication
   * const juryApplication = await prisma.juryApplication.upsert({
   *   create: {
   *     // ... data to create a JuryApplication
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the JuryApplication we want to update
   *   }
   * })
   */
  upsert<T extends JuryApplicationUpsertArgs>(args: Prisma.SelectSubset<T, JuryApplicationUpsertArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of JuryApplications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationCountArgs} args - Arguments to filter JuryApplications to count.
   * @example
   * // Count the number of JuryApplications
   * const count = await prisma.juryApplication.count({
   *   where: {
   *     // ... the filter for the JuryApplications we want to count
   *   }
   * })
  **/
  count<T extends JuryApplicationCountArgs>(
    args?: Prisma.Subset<T, JuryApplicationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], JuryApplicationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a JuryApplication.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends JuryApplicationAggregateArgs>(args: Prisma.Subset<T, JuryApplicationAggregateArgs>): Prisma.PrismaPromise<GetJuryApplicationAggregateType<T>>

  /**
   * Group by JuryApplication.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends JuryApplicationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: JuryApplicationGroupByArgs['orderBy'] }
      : { orderBy?: JuryApplicationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, JuryApplicationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetJuryApplicationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the JuryApplication model
 */
readonly fields: JuryApplicationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for JuryApplication.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__JuryApplicationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  files<T extends Prisma.JuryApplication$filesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.JuryApplication$filesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the JuryApplication model
 */
export interface JuryApplicationFieldRefs {
  readonly id: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly fullName: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly email: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly phone: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly country: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly city: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly professionalTitle: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly yearsExperience: Prisma.FieldRef<"JuryApplication", 'Int'>
  readonly employerAffiliation: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly membershipStatus: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly membershipLevel: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly previousJudgingExperience: Prisma.FieldRef<"JuryApplication", 'Boolean'>
  readonly previousJudgingDetails: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly pastWinner: Prisma.FieldRef<"JuryApplication", 'Boolean'>
  readonly pastWinnerYear: Prisma.FieldRef<"JuryApplication", 'Int'>
  readonly expertiseAreas: Prisma.FieldRef<"JuryApplication", 'String[]'>
  readonly professionalBio: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly professionalWebsite: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly conflictDisclosure: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly confidentialityAgreementAccepted: Prisma.FieldRef<"JuryApplication", 'Boolean'>
  readonly motivation: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly status: Prisma.FieldRef<"JuryApplication", 'ApplicationStatus'>
  readonly adminNotes: Prisma.FieldRef<"JuryApplication", 'String'>
  readonly reviewedAt: Prisma.FieldRef<"JuryApplication", 'DateTime'>
  readonly submittedAt: Prisma.FieldRef<"JuryApplication", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"JuryApplication", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"JuryApplication", 'DateTime'>
}
    

// Custom InputTypes
/**
 * JuryApplication findUnique
 */
export type JuryApplicationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationInclude<ExtArgs> | null
  /**
   * Filter, which JuryApplication to fetch.
   */
  where: Prisma.JuryApplicationWhereUniqueInput
}

/**
 * JuryApplication findUniqueOrThrow
 */
export type JuryApplicationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationInclude<ExtArgs> | null
  /**
   * Filter, which JuryApplication to fetch.
   */
  where: Prisma.JuryApplicationWhereUniqueInput
}

/**
 * JuryApplication findFirst
 */
export type JuryApplicationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationInclude<ExtArgs> | null
  /**
   * Filter, which JuryApplication to fetch.
   */
  where?: Prisma.JuryApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JuryApplications to fetch.
   */
  orderBy?: Prisma.JuryApplicationOrderByWithRelationInput | Prisma.JuryApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JuryApplications.
   */
  cursor?: Prisma.JuryApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JuryApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JuryApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JuryApplications.
   */
  distinct?: Prisma.JuryApplicationScalarFieldEnum | Prisma.JuryApplicationScalarFieldEnum[]
}

/**
 * JuryApplication findFirstOrThrow
 */
export type JuryApplicationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationInclude<ExtArgs> | null
  /**
   * Filter, which JuryApplication to fetch.
   */
  where?: Prisma.JuryApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JuryApplications to fetch.
   */
  orderBy?: Prisma.JuryApplicationOrderByWithRelationInput | Prisma.JuryApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JuryApplications.
   */
  cursor?: Prisma.JuryApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JuryApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JuryApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JuryApplications.
   */
  distinct?: Prisma.JuryApplicationScalarFieldEnum | Prisma.JuryApplicationScalarFieldEnum[]
}

/**
 * JuryApplication findMany
 */
export type JuryApplicationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationInclude<ExtArgs> | null
  /**
   * Filter, which JuryApplications to fetch.
   */
  where?: Prisma.JuryApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JuryApplications to fetch.
   */
  orderBy?: Prisma.JuryApplicationOrderByWithRelationInput | Prisma.JuryApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing JuryApplications.
   */
  cursor?: Prisma.JuryApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JuryApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JuryApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JuryApplications.
   */
  distinct?: Prisma.JuryApplicationScalarFieldEnum | Prisma.JuryApplicationScalarFieldEnum[]
}

/**
 * JuryApplication create
 */
export type JuryApplicationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationInclude<ExtArgs> | null
  /**
   * The data needed to create a JuryApplication.
   */
  data: Prisma.XOR<Prisma.JuryApplicationCreateInput, Prisma.JuryApplicationUncheckedCreateInput>
}

/**
 * JuryApplication createMany
 */
export type JuryApplicationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many JuryApplications.
   */
  data: Prisma.JuryApplicationCreateManyInput | Prisma.JuryApplicationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * JuryApplication createManyAndReturn
 */
export type JuryApplicationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * The data used to create many JuryApplications.
   */
  data: Prisma.JuryApplicationCreateManyInput | Prisma.JuryApplicationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * JuryApplication update
 */
export type JuryApplicationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationInclude<ExtArgs> | null
  /**
   * The data needed to update a JuryApplication.
   */
  data: Prisma.XOR<Prisma.JuryApplicationUpdateInput, Prisma.JuryApplicationUncheckedUpdateInput>
  /**
   * Choose, which JuryApplication to update.
   */
  where: Prisma.JuryApplicationWhereUniqueInput
}

/**
 * JuryApplication updateMany
 */
export type JuryApplicationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update JuryApplications.
   */
  data: Prisma.XOR<Prisma.JuryApplicationUpdateManyMutationInput, Prisma.JuryApplicationUncheckedUpdateManyInput>
  /**
   * Filter which JuryApplications to update
   */
  where?: Prisma.JuryApplicationWhereInput
  /**
   * Limit how many JuryApplications to update.
   */
  limit?: number
}

/**
 * JuryApplication updateManyAndReturn
 */
export type JuryApplicationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * The data used to update JuryApplications.
   */
  data: Prisma.XOR<Prisma.JuryApplicationUpdateManyMutationInput, Prisma.JuryApplicationUncheckedUpdateManyInput>
  /**
   * Filter which JuryApplications to update
   */
  where?: Prisma.JuryApplicationWhereInput
  /**
   * Limit how many JuryApplications to update.
   */
  limit?: number
}

/**
 * JuryApplication upsert
 */
export type JuryApplicationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationInclude<ExtArgs> | null
  /**
   * The filter to search for the JuryApplication to update in case it exists.
   */
  where: Prisma.JuryApplicationWhereUniqueInput
  /**
   * In case the JuryApplication found by the `where` argument doesn't exist, create a new JuryApplication with this data.
   */
  create: Prisma.XOR<Prisma.JuryApplicationCreateInput, Prisma.JuryApplicationUncheckedCreateInput>
  /**
   * In case the JuryApplication was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.JuryApplicationUpdateInput, Prisma.JuryApplicationUncheckedUpdateInput>
}

/**
 * JuryApplication delete
 */
export type JuryApplicationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationInclude<ExtArgs> | null
  /**
   * Filter which JuryApplication to delete.
   */
  where: Prisma.JuryApplicationWhereUniqueInput
}

/**
 * JuryApplication deleteMany
 */
export type JuryApplicationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JuryApplications to delete
   */
  where?: Prisma.JuryApplicationWhereInput
  /**
   * Limit how many JuryApplications to delete.
   */
  limit?: number
}

/**
 * JuryApplication.files
 */
export type JuryApplication$filesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileInclude<ExtArgs> | null
  where?: Prisma.JuryApplicationFileWhereInput
  orderBy?: Prisma.JuryApplicationFileOrderByWithRelationInput | Prisma.JuryApplicationFileOrderByWithRelationInput[]
  cursor?: Prisma.JuryApplicationFileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.JuryApplicationFileScalarFieldEnum | Prisma.JuryApplicationFileScalarFieldEnum[]
}

/**
 * JuryApplication without action
 */
export type JuryApplicationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplication
   */
  select?: Prisma.JuryApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplication
   */
  omit?: Prisma.JuryApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationInclude<ExtArgs> | null
}
