
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `JuryApplicationFile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model JuryApplicationFile
 * 
 */
export type JuryApplicationFileModel = runtime.Types.Result.DefaultSelection<Prisma.$JuryApplicationFilePayload>

export type AggregateJuryApplicationFile = {
  _count: JuryApplicationFileCountAggregateOutputType | null
  _avg: JuryApplicationFileAvgAggregateOutputType | null
  _sum: JuryApplicationFileSumAggregateOutputType | null
  _min: JuryApplicationFileMinAggregateOutputType | null
  _max: JuryApplicationFileMaxAggregateOutputType | null
}

export type JuryApplicationFileAvgAggregateOutputType = {
  fileSize: number | null
}

export type JuryApplicationFileSumAggregateOutputType = {
  fileSize: number | null
}

export type JuryApplicationFileMinAggregateOutputType = {
  id: string | null
  juryApplicationId: string | null
  fieldKey: string | null
  fileName: string | null
  mimeType: string | null
  fileSize: number | null
  storageKey: string | null
  createdAt: Date | null
}

export type JuryApplicationFileMaxAggregateOutputType = {
  id: string | null
  juryApplicationId: string | null
  fieldKey: string | null
  fileName: string | null
  mimeType: string | null
  fileSize: number | null
  storageKey: string | null
  createdAt: Date | null
}

export type JuryApplicationFileCountAggregateOutputType = {
  id: number
  juryApplicationId: number
  fieldKey: number
  fileName: number
  mimeType: number
  fileSize: number
  storageKey: number
  createdAt: number
  _all: number
}


export type JuryApplicationFileAvgAggregateInputType = {
  fileSize?: true
}

export type JuryApplicationFileSumAggregateInputType = {
  fileSize?: true
}

export type JuryApplicationFileMinAggregateInputType = {
  id?: true
  juryApplicationId?: true
  fieldKey?: true
  fileName?: true
  mimeType?: true
  fileSize?: true
  storageKey?: true
  createdAt?: true
}

export type JuryApplicationFileMaxAggregateInputType = {
  id?: true
  juryApplicationId?: true
  fieldKey?: true
  fileName?: true
  mimeType?: true
  fileSize?: true
  storageKey?: true
  createdAt?: true
}

export type JuryApplicationFileCountAggregateInputType = {
  id?: true
  juryApplicationId?: true
  fieldKey?: true
  fileName?: true
  mimeType?: true
  fileSize?: true
  storageKey?: true
  createdAt?: true
  _all?: true
}

export type JuryApplicationFileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JuryApplicationFile to aggregate.
   */
  where?: Prisma.JuryApplicationFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JuryApplicationFiles to fetch.
   */
  orderBy?: Prisma.JuryApplicationFileOrderByWithRelationInput | Prisma.JuryApplicationFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.JuryApplicationFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JuryApplicationFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JuryApplicationFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned JuryApplicationFiles
  **/
  _count?: true | JuryApplicationFileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: JuryApplicationFileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: JuryApplicationFileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: JuryApplicationFileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: JuryApplicationFileMaxAggregateInputType
}

export type GetJuryApplicationFileAggregateType<T extends JuryApplicationFileAggregateArgs> = {
      [P in keyof T & keyof AggregateJuryApplicationFile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateJuryApplicationFile[P]>
    : Prisma.GetScalarType<T[P], AggregateJuryApplicationFile[P]>
}




export type JuryApplicationFileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JuryApplicationFileWhereInput
  orderBy?: Prisma.JuryApplicationFileOrderByWithAggregationInput | Prisma.JuryApplicationFileOrderByWithAggregationInput[]
  by: Prisma.JuryApplicationFileScalarFieldEnum[] | Prisma.JuryApplicationFileScalarFieldEnum
  having?: Prisma.JuryApplicationFileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: JuryApplicationFileCountAggregateInputType | true
  _avg?: JuryApplicationFileAvgAggregateInputType
  _sum?: JuryApplicationFileSumAggregateInputType
  _min?: JuryApplicationFileMinAggregateInputType
  _max?: JuryApplicationFileMaxAggregateInputType
}

export type JuryApplicationFileGroupByOutputType = {
  id: string
  juryApplicationId: string
  fieldKey: string
  fileName: string
  mimeType: string
  fileSize: number
  storageKey: string | null
  createdAt: Date
  _count: JuryApplicationFileCountAggregateOutputType | null
  _avg: JuryApplicationFileAvgAggregateOutputType | null
  _sum: JuryApplicationFileSumAggregateOutputType | null
  _min: JuryApplicationFileMinAggregateOutputType | null
  _max: JuryApplicationFileMaxAggregateOutputType | null
}

export type GetJuryApplicationFileGroupByPayload<T extends JuryApplicationFileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<JuryApplicationFileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof JuryApplicationFileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], JuryApplicationFileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], JuryApplicationFileGroupByOutputType[P]>
      }
    >
  >



export type JuryApplicationFileWhereInput = {
  AND?: Prisma.JuryApplicationFileWhereInput | Prisma.JuryApplicationFileWhereInput[]
  OR?: Prisma.JuryApplicationFileWhereInput[]
  NOT?: Prisma.JuryApplicationFileWhereInput | Prisma.JuryApplicationFileWhereInput[]
  id?: Prisma.StringFilter<"JuryApplicationFile"> | string
  juryApplicationId?: Prisma.StringFilter<"JuryApplicationFile"> | string
  fieldKey?: Prisma.StringFilter<"JuryApplicationFile"> | string
  fileName?: Prisma.StringFilter<"JuryApplicationFile"> | string
  mimeType?: Prisma.StringFilter<"JuryApplicationFile"> | string
  fileSize?: Prisma.IntFilter<"JuryApplicationFile"> | number
  storageKey?: Prisma.StringNullableFilter<"JuryApplicationFile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"JuryApplicationFile"> | Date | string
  juryApplication?: Prisma.XOR<Prisma.JuryApplicationScalarRelationFilter, Prisma.JuryApplicationWhereInput>
}

export type JuryApplicationFileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  juryApplicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  storageKey?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  juryApplication?: Prisma.JuryApplicationOrderByWithRelationInput
}

export type JuryApplicationFileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.JuryApplicationFileWhereInput | Prisma.JuryApplicationFileWhereInput[]
  OR?: Prisma.JuryApplicationFileWhereInput[]
  NOT?: Prisma.JuryApplicationFileWhereInput | Prisma.JuryApplicationFileWhereInput[]
  juryApplicationId?: Prisma.StringFilter<"JuryApplicationFile"> | string
  fieldKey?: Prisma.StringFilter<"JuryApplicationFile"> | string
  fileName?: Prisma.StringFilter<"JuryApplicationFile"> | string
  mimeType?: Prisma.StringFilter<"JuryApplicationFile"> | string
  fileSize?: Prisma.IntFilter<"JuryApplicationFile"> | number
  storageKey?: Prisma.StringNullableFilter<"JuryApplicationFile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"JuryApplicationFile"> | Date | string
  juryApplication?: Prisma.XOR<Prisma.JuryApplicationScalarRelationFilter, Prisma.JuryApplicationWhereInput>
}, "id">

export type JuryApplicationFileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  juryApplicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  storageKey?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.JuryApplicationFileCountOrderByAggregateInput
  _avg?: Prisma.JuryApplicationFileAvgOrderByAggregateInput
  _max?: Prisma.JuryApplicationFileMaxOrderByAggregateInput
  _min?: Prisma.JuryApplicationFileMinOrderByAggregateInput
  _sum?: Prisma.JuryApplicationFileSumOrderByAggregateInput
}

export type JuryApplicationFileScalarWhereWithAggregatesInput = {
  AND?: Prisma.JuryApplicationFileScalarWhereWithAggregatesInput | Prisma.JuryApplicationFileScalarWhereWithAggregatesInput[]
  OR?: Prisma.JuryApplicationFileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.JuryApplicationFileScalarWhereWithAggregatesInput | Prisma.JuryApplicationFileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"JuryApplicationFile"> | string
  juryApplicationId?: Prisma.StringWithAggregatesFilter<"JuryApplicationFile"> | string
  fieldKey?: Prisma.StringWithAggregatesFilter<"JuryApplicationFile"> | string
  fileName?: Prisma.StringWithAggregatesFilter<"JuryApplicationFile"> | string
  mimeType?: Prisma.StringWithAggregatesFilter<"JuryApplicationFile"> | string
  fileSize?: Prisma.IntWithAggregatesFilter<"JuryApplicationFile"> | number
  storageKey?: Prisma.StringNullableWithAggregatesFilter<"JuryApplicationFile"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"JuryApplicationFile"> | Date | string
}

export type JuryApplicationFileCreateInput = {
  id?: string
  fieldKey: string
  fileName: string
  mimeType: string
  fileSize: number
  storageKey?: string | null
  createdAt?: Date | string
  juryApplication: Prisma.JuryApplicationCreateNestedOneWithoutFilesInput
}

export type JuryApplicationFileUncheckedCreateInput = {
  id?: string
  juryApplicationId: string
  fieldKey: string
  fileName: string
  mimeType: string
  fileSize: number
  storageKey?: string | null
  createdAt?: Date | string
}

export type JuryApplicationFileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  storageKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  juryApplication?: Prisma.JuryApplicationUpdateOneRequiredWithoutFilesNestedInput
}

export type JuryApplicationFileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  juryApplicationId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  storageKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JuryApplicationFileCreateManyInput = {
  id?: string
  juryApplicationId: string
  fieldKey: string
  fileName: string
  mimeType: string
  fileSize: number
  storageKey?: string | null
  createdAt?: Date | string
}

export type JuryApplicationFileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  storageKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JuryApplicationFileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  juryApplicationId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  storageKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JuryApplicationFileListRelationFilter = {
  every?: Prisma.JuryApplicationFileWhereInput
  some?: Prisma.JuryApplicationFileWhereInput
  none?: Prisma.JuryApplicationFileWhereInput
}

export type JuryApplicationFileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type JuryApplicationFileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  juryApplicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  storageKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type JuryApplicationFileAvgOrderByAggregateInput = {
  fileSize?: Prisma.SortOrder
}

export type JuryApplicationFileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  juryApplicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  storageKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type JuryApplicationFileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  juryApplicationId?: Prisma.SortOrder
  fieldKey?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  storageKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type JuryApplicationFileSumOrderByAggregateInput = {
  fileSize?: Prisma.SortOrder
}

export type JuryApplicationFileCreateNestedManyWithoutJuryApplicationInput = {
  create?: Prisma.XOR<Prisma.JuryApplicationFileCreateWithoutJuryApplicationInput, Prisma.JuryApplicationFileUncheckedCreateWithoutJuryApplicationInput> | Prisma.JuryApplicationFileCreateWithoutJuryApplicationInput[] | Prisma.JuryApplicationFileUncheckedCreateWithoutJuryApplicationInput[]
  connectOrCreate?: Prisma.JuryApplicationFileCreateOrConnectWithoutJuryApplicationInput | Prisma.JuryApplicationFileCreateOrConnectWithoutJuryApplicationInput[]
  createMany?: Prisma.JuryApplicationFileCreateManyJuryApplicationInputEnvelope
  connect?: Prisma.JuryApplicationFileWhereUniqueInput | Prisma.JuryApplicationFileWhereUniqueInput[]
}

export type JuryApplicationFileUncheckedCreateNestedManyWithoutJuryApplicationInput = {
  create?: Prisma.XOR<Prisma.JuryApplicationFileCreateWithoutJuryApplicationInput, Prisma.JuryApplicationFileUncheckedCreateWithoutJuryApplicationInput> | Prisma.JuryApplicationFileCreateWithoutJuryApplicationInput[] | Prisma.JuryApplicationFileUncheckedCreateWithoutJuryApplicationInput[]
  connectOrCreate?: Prisma.JuryApplicationFileCreateOrConnectWithoutJuryApplicationInput | Prisma.JuryApplicationFileCreateOrConnectWithoutJuryApplicationInput[]
  createMany?: Prisma.JuryApplicationFileCreateManyJuryApplicationInputEnvelope
  connect?: Prisma.JuryApplicationFileWhereUniqueInput | Prisma.JuryApplicationFileWhereUniqueInput[]
}

export type JuryApplicationFileUpdateManyWithoutJuryApplicationNestedInput = {
  create?: Prisma.XOR<Prisma.JuryApplicationFileCreateWithoutJuryApplicationInput, Prisma.JuryApplicationFileUncheckedCreateWithoutJuryApplicationInput> | Prisma.JuryApplicationFileCreateWithoutJuryApplicationInput[] | Prisma.JuryApplicationFileUncheckedCreateWithoutJuryApplicationInput[]
  connectOrCreate?: Prisma.JuryApplicationFileCreateOrConnectWithoutJuryApplicationInput | Prisma.JuryApplicationFileCreateOrConnectWithoutJuryApplicationInput[]
  upsert?: Prisma.JuryApplicationFileUpsertWithWhereUniqueWithoutJuryApplicationInput | Prisma.JuryApplicationFileUpsertWithWhereUniqueWithoutJuryApplicationInput[]
  createMany?: Prisma.JuryApplicationFileCreateManyJuryApplicationInputEnvelope
  set?: Prisma.JuryApplicationFileWhereUniqueInput | Prisma.JuryApplicationFileWhereUniqueInput[]
  disconnect?: Prisma.JuryApplicationFileWhereUniqueInput | Prisma.JuryApplicationFileWhereUniqueInput[]
  delete?: Prisma.JuryApplicationFileWhereUniqueInput | Prisma.JuryApplicationFileWhereUniqueInput[]
  connect?: Prisma.JuryApplicationFileWhereUniqueInput | Prisma.JuryApplicationFileWhereUniqueInput[]
  update?: Prisma.JuryApplicationFileUpdateWithWhereUniqueWithoutJuryApplicationInput | Prisma.JuryApplicationFileUpdateWithWhereUniqueWithoutJuryApplicationInput[]
  updateMany?: Prisma.JuryApplicationFileUpdateManyWithWhereWithoutJuryApplicationInput | Prisma.JuryApplicationFileUpdateManyWithWhereWithoutJuryApplicationInput[]
  deleteMany?: Prisma.JuryApplicationFileScalarWhereInput | Prisma.JuryApplicationFileScalarWhereInput[]
}

export type JuryApplicationFileUncheckedUpdateManyWithoutJuryApplicationNestedInput = {
  create?: Prisma.XOR<Prisma.JuryApplicationFileCreateWithoutJuryApplicationInput, Prisma.JuryApplicationFileUncheckedCreateWithoutJuryApplicationInput> | Prisma.JuryApplicationFileCreateWithoutJuryApplicationInput[] | Prisma.JuryApplicationFileUncheckedCreateWithoutJuryApplicationInput[]
  connectOrCreate?: Prisma.JuryApplicationFileCreateOrConnectWithoutJuryApplicationInput | Prisma.JuryApplicationFileCreateOrConnectWithoutJuryApplicationInput[]
  upsert?: Prisma.JuryApplicationFileUpsertWithWhereUniqueWithoutJuryApplicationInput | Prisma.JuryApplicationFileUpsertWithWhereUniqueWithoutJuryApplicationInput[]
  createMany?: Prisma.JuryApplicationFileCreateManyJuryApplicationInputEnvelope
  set?: Prisma.JuryApplicationFileWhereUniqueInput | Prisma.JuryApplicationFileWhereUniqueInput[]
  disconnect?: Prisma.JuryApplicationFileWhereUniqueInput | Prisma.JuryApplicationFileWhereUniqueInput[]
  delete?: Prisma.JuryApplicationFileWhereUniqueInput | Prisma.JuryApplicationFileWhereUniqueInput[]
  connect?: Prisma.JuryApplicationFileWhereUniqueInput | Prisma.JuryApplicationFileWhereUniqueInput[]
  update?: Prisma.JuryApplicationFileUpdateWithWhereUniqueWithoutJuryApplicationInput | Prisma.JuryApplicationFileUpdateWithWhereUniqueWithoutJuryApplicationInput[]
  updateMany?: Prisma.JuryApplicationFileUpdateManyWithWhereWithoutJuryApplicationInput | Prisma.JuryApplicationFileUpdateManyWithWhereWithoutJuryApplicationInput[]
  deleteMany?: Prisma.JuryApplicationFileScalarWhereInput | Prisma.JuryApplicationFileScalarWhereInput[]
}

export type JuryApplicationFileCreateWithoutJuryApplicationInput = {
  id?: string
  fieldKey: string
  fileName: string
  mimeType: string
  fileSize: number
  storageKey?: string | null
  createdAt?: Date | string
}

export type JuryApplicationFileUncheckedCreateWithoutJuryApplicationInput = {
  id?: string
  fieldKey: string
  fileName: string
  mimeType: string
  fileSize: number
  storageKey?: string | null
  createdAt?: Date | string
}

export type JuryApplicationFileCreateOrConnectWithoutJuryApplicationInput = {
  where: Prisma.JuryApplicationFileWhereUniqueInput
  create: Prisma.XOR<Prisma.JuryApplicationFileCreateWithoutJuryApplicationInput, Prisma.JuryApplicationFileUncheckedCreateWithoutJuryApplicationInput>
}

export type JuryApplicationFileCreateManyJuryApplicationInputEnvelope = {
  data: Prisma.JuryApplicationFileCreateManyJuryApplicationInput | Prisma.JuryApplicationFileCreateManyJuryApplicationInput[]
  skipDuplicates?: boolean
}

export type JuryApplicationFileUpsertWithWhereUniqueWithoutJuryApplicationInput = {
  where: Prisma.JuryApplicationFileWhereUniqueInput
  update: Prisma.XOR<Prisma.JuryApplicationFileUpdateWithoutJuryApplicationInput, Prisma.JuryApplicationFileUncheckedUpdateWithoutJuryApplicationInput>
  create: Prisma.XOR<Prisma.JuryApplicationFileCreateWithoutJuryApplicationInput, Prisma.JuryApplicationFileUncheckedCreateWithoutJuryApplicationInput>
}

export type JuryApplicationFileUpdateWithWhereUniqueWithoutJuryApplicationInput = {
  where: Prisma.JuryApplicationFileWhereUniqueInput
  data: Prisma.XOR<Prisma.JuryApplicationFileUpdateWithoutJuryApplicationInput, Prisma.JuryApplicationFileUncheckedUpdateWithoutJuryApplicationInput>
}

export type JuryApplicationFileUpdateManyWithWhereWithoutJuryApplicationInput = {
  where: Prisma.JuryApplicationFileScalarWhereInput
  data: Prisma.XOR<Prisma.JuryApplicationFileUpdateManyMutationInput, Prisma.JuryApplicationFileUncheckedUpdateManyWithoutJuryApplicationInput>
}

export type JuryApplicationFileScalarWhereInput = {
  AND?: Prisma.JuryApplicationFileScalarWhereInput | Prisma.JuryApplicationFileScalarWhereInput[]
  OR?: Prisma.JuryApplicationFileScalarWhereInput[]
  NOT?: Prisma.JuryApplicationFileScalarWhereInput | Prisma.JuryApplicationFileScalarWhereInput[]
  id?: Prisma.StringFilter<"JuryApplicationFile"> | string
  juryApplicationId?: Prisma.StringFilter<"JuryApplicationFile"> | string
  fieldKey?: Prisma.StringFilter<"JuryApplicationFile"> | string
  fileName?: Prisma.StringFilter<"JuryApplicationFile"> | string
  mimeType?: Prisma.StringFilter<"JuryApplicationFile"> | string
  fileSize?: Prisma.IntFilter<"JuryApplicationFile"> | number
  storageKey?: Prisma.StringNullableFilter<"JuryApplicationFile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"JuryApplicationFile"> | Date | string
}

export type JuryApplicationFileCreateManyJuryApplicationInput = {
  id?: string
  fieldKey: string
  fileName: string
  mimeType: string
  fileSize: number
  storageKey?: string | null
  createdAt?: Date | string
}

export type JuryApplicationFileUpdateWithoutJuryApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  storageKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JuryApplicationFileUncheckedUpdateWithoutJuryApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  storageKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JuryApplicationFileUncheckedUpdateManyWithoutJuryApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldKey?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  storageKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type JuryApplicationFileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  juryApplicationId?: boolean
  fieldKey?: boolean
  fileName?: boolean
  mimeType?: boolean
  fileSize?: boolean
  storageKey?: boolean
  createdAt?: boolean
  juryApplication?: boolean | Prisma.JuryApplicationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["juryApplicationFile"]>

export type JuryApplicationFileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  juryApplicationId?: boolean
  fieldKey?: boolean
  fileName?: boolean
  mimeType?: boolean
  fileSize?: boolean
  storageKey?: boolean
  createdAt?: boolean
  juryApplication?: boolean | Prisma.JuryApplicationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["juryApplicationFile"]>

export type JuryApplicationFileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  juryApplicationId?: boolean
  fieldKey?: boolean
  fileName?: boolean
  mimeType?: boolean
  fileSize?: boolean
  storageKey?: boolean
  createdAt?: boolean
  juryApplication?: boolean | Prisma.JuryApplicationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["juryApplicationFile"]>

export type JuryApplicationFileSelectScalar = {
  id?: boolean
  juryApplicationId?: boolean
  fieldKey?: boolean
  fileName?: boolean
  mimeType?: boolean
  fileSize?: boolean
  storageKey?: boolean
  createdAt?: boolean
}

export type JuryApplicationFileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "juryApplicationId" | "fieldKey" | "fileName" | "mimeType" | "fileSize" | "storageKey" | "createdAt", ExtArgs["result"]["juryApplicationFile"]>
export type JuryApplicationFileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  juryApplication?: boolean | Prisma.JuryApplicationDefaultArgs<ExtArgs>
}
export type JuryApplicationFileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  juryApplication?: boolean | Prisma.JuryApplicationDefaultArgs<ExtArgs>
}
export type JuryApplicationFileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  juryApplication?: boolean | Prisma.JuryApplicationDefaultArgs<ExtArgs>
}

export type $JuryApplicationFilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "JuryApplicationFile"
  objects: {
    juryApplication: Prisma.$JuryApplicationPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    juryApplicationId: string
    fieldKey: string
    fileName: string
    mimeType: string
    fileSize: number
    storageKey: string | null
    createdAt: Date
  }, ExtArgs["result"]["juryApplicationFile"]>
  composites: {}
}

export type JuryApplicationFileGetPayload<S extends boolean | null | undefined | JuryApplicationFileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload, S>

export type JuryApplicationFileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<JuryApplicationFileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: JuryApplicationFileCountAggregateInputType | true
  }

export interface JuryApplicationFileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['JuryApplicationFile'], meta: { name: 'JuryApplicationFile' } }
  /**
   * Find zero or one JuryApplicationFile that matches the filter.
   * @param {JuryApplicationFileFindUniqueArgs} args - Arguments to find a JuryApplicationFile
   * @example
   * // Get one JuryApplicationFile
   * const juryApplicationFile = await prisma.juryApplicationFile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends JuryApplicationFileFindUniqueArgs>(args: Prisma.SelectSubset<T, JuryApplicationFileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one JuryApplicationFile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {JuryApplicationFileFindUniqueOrThrowArgs} args - Arguments to find a JuryApplicationFile
   * @example
   * // Get one JuryApplicationFile
   * const juryApplicationFile = await prisma.juryApplicationFile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends JuryApplicationFileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, JuryApplicationFileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JuryApplicationFile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationFileFindFirstArgs} args - Arguments to find a JuryApplicationFile
   * @example
   * // Get one JuryApplicationFile
   * const juryApplicationFile = await prisma.juryApplicationFile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends JuryApplicationFileFindFirstArgs>(args?: Prisma.SelectSubset<T, JuryApplicationFileFindFirstArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JuryApplicationFile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationFileFindFirstOrThrowArgs} args - Arguments to find a JuryApplicationFile
   * @example
   * // Get one JuryApplicationFile
   * const juryApplicationFile = await prisma.juryApplicationFile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends JuryApplicationFileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, JuryApplicationFileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more JuryApplicationFiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationFileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all JuryApplicationFiles
   * const juryApplicationFiles = await prisma.juryApplicationFile.findMany()
   * 
   * // Get first 10 JuryApplicationFiles
   * const juryApplicationFiles = await prisma.juryApplicationFile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const juryApplicationFileWithIdOnly = await prisma.juryApplicationFile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends JuryApplicationFileFindManyArgs>(args?: Prisma.SelectSubset<T, JuryApplicationFileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a JuryApplicationFile.
   * @param {JuryApplicationFileCreateArgs} args - Arguments to create a JuryApplicationFile.
   * @example
   * // Create one JuryApplicationFile
   * const JuryApplicationFile = await prisma.juryApplicationFile.create({
   *   data: {
   *     // ... data to create a JuryApplicationFile
   *   }
   * })
   * 
   */
  create<T extends JuryApplicationFileCreateArgs>(args: Prisma.SelectSubset<T, JuryApplicationFileCreateArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many JuryApplicationFiles.
   * @param {JuryApplicationFileCreateManyArgs} args - Arguments to create many JuryApplicationFiles.
   * @example
   * // Create many JuryApplicationFiles
   * const juryApplicationFile = await prisma.juryApplicationFile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends JuryApplicationFileCreateManyArgs>(args?: Prisma.SelectSubset<T, JuryApplicationFileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many JuryApplicationFiles and returns the data saved in the database.
   * @param {JuryApplicationFileCreateManyAndReturnArgs} args - Arguments to create many JuryApplicationFiles.
   * @example
   * // Create many JuryApplicationFiles
   * const juryApplicationFile = await prisma.juryApplicationFile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many JuryApplicationFiles and only return the `id`
   * const juryApplicationFileWithIdOnly = await prisma.juryApplicationFile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends JuryApplicationFileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, JuryApplicationFileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a JuryApplicationFile.
   * @param {JuryApplicationFileDeleteArgs} args - Arguments to delete one JuryApplicationFile.
   * @example
   * // Delete one JuryApplicationFile
   * const JuryApplicationFile = await prisma.juryApplicationFile.delete({
   *   where: {
   *     // ... filter to delete one JuryApplicationFile
   *   }
   * })
   * 
   */
  delete<T extends JuryApplicationFileDeleteArgs>(args: Prisma.SelectSubset<T, JuryApplicationFileDeleteArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one JuryApplicationFile.
   * @param {JuryApplicationFileUpdateArgs} args - Arguments to update one JuryApplicationFile.
   * @example
   * // Update one JuryApplicationFile
   * const juryApplicationFile = await prisma.juryApplicationFile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends JuryApplicationFileUpdateArgs>(args: Prisma.SelectSubset<T, JuryApplicationFileUpdateArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more JuryApplicationFiles.
   * @param {JuryApplicationFileDeleteManyArgs} args - Arguments to filter JuryApplicationFiles to delete.
   * @example
   * // Delete a few JuryApplicationFiles
   * const { count } = await prisma.juryApplicationFile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends JuryApplicationFileDeleteManyArgs>(args?: Prisma.SelectSubset<T, JuryApplicationFileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JuryApplicationFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationFileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many JuryApplicationFiles
   * const juryApplicationFile = await prisma.juryApplicationFile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends JuryApplicationFileUpdateManyArgs>(args: Prisma.SelectSubset<T, JuryApplicationFileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JuryApplicationFiles and returns the data updated in the database.
   * @param {JuryApplicationFileUpdateManyAndReturnArgs} args - Arguments to update many JuryApplicationFiles.
   * @example
   * // Update many JuryApplicationFiles
   * const juryApplicationFile = await prisma.juryApplicationFile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more JuryApplicationFiles and only return the `id`
   * const juryApplicationFileWithIdOnly = await prisma.juryApplicationFile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends JuryApplicationFileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, JuryApplicationFileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one JuryApplicationFile.
   * @param {JuryApplicationFileUpsertArgs} args - Arguments to update or create a JuryApplicationFile.
   * @example
   * // Update or create a JuryApplicationFile
   * const juryApplicationFile = await prisma.juryApplicationFile.upsert({
   *   create: {
   *     // ... data to create a JuryApplicationFile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the JuryApplicationFile we want to update
   *   }
   * })
   */
  upsert<T extends JuryApplicationFileUpsertArgs>(args: Prisma.SelectSubset<T, JuryApplicationFileUpsertArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationFileClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationFilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of JuryApplicationFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationFileCountArgs} args - Arguments to filter JuryApplicationFiles to count.
   * @example
   * // Count the number of JuryApplicationFiles
   * const count = await prisma.juryApplicationFile.count({
   *   where: {
   *     // ... the filter for the JuryApplicationFiles we want to count
   *   }
   * })
  **/
  count<T extends JuryApplicationFileCountArgs>(
    args?: Prisma.Subset<T, JuryApplicationFileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], JuryApplicationFileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a JuryApplicationFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationFileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends JuryApplicationFileAggregateArgs>(args: Prisma.Subset<T, JuryApplicationFileAggregateArgs>): Prisma.PrismaPromise<GetJuryApplicationFileAggregateType<T>>

  /**
   * Group by JuryApplicationFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JuryApplicationFileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends JuryApplicationFileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: JuryApplicationFileGroupByArgs['orderBy'] }
      : { orderBy?: JuryApplicationFileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, JuryApplicationFileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetJuryApplicationFileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the JuryApplicationFile model
 */
readonly fields: JuryApplicationFileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for JuryApplicationFile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__JuryApplicationFileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  juryApplication<T extends Prisma.JuryApplicationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.JuryApplicationDefaultArgs<ExtArgs>>): Prisma.Prisma__JuryApplicationClient<runtime.Types.Result.GetResult<Prisma.$JuryApplicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the JuryApplicationFile model
 */
export interface JuryApplicationFileFieldRefs {
  readonly id: Prisma.FieldRef<"JuryApplicationFile", 'String'>
  readonly juryApplicationId: Prisma.FieldRef<"JuryApplicationFile", 'String'>
  readonly fieldKey: Prisma.FieldRef<"JuryApplicationFile", 'String'>
  readonly fileName: Prisma.FieldRef<"JuryApplicationFile", 'String'>
  readonly mimeType: Prisma.FieldRef<"JuryApplicationFile", 'String'>
  readonly fileSize: Prisma.FieldRef<"JuryApplicationFile", 'Int'>
  readonly storageKey: Prisma.FieldRef<"JuryApplicationFile", 'String'>
  readonly createdAt: Prisma.FieldRef<"JuryApplicationFile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * JuryApplicationFile findUnique
 */
export type JuryApplicationFileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileInclude<ExtArgs> | null
  /**
   * Filter, which JuryApplicationFile to fetch.
   */
  where: Prisma.JuryApplicationFileWhereUniqueInput
}

/**
 * JuryApplicationFile findUniqueOrThrow
 */
export type JuryApplicationFileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileInclude<ExtArgs> | null
  /**
   * Filter, which JuryApplicationFile to fetch.
   */
  where: Prisma.JuryApplicationFileWhereUniqueInput
}

/**
 * JuryApplicationFile findFirst
 */
export type JuryApplicationFileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileInclude<ExtArgs> | null
  /**
   * Filter, which JuryApplicationFile to fetch.
   */
  where?: Prisma.JuryApplicationFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JuryApplicationFiles to fetch.
   */
  orderBy?: Prisma.JuryApplicationFileOrderByWithRelationInput | Prisma.JuryApplicationFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JuryApplicationFiles.
   */
  cursor?: Prisma.JuryApplicationFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JuryApplicationFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JuryApplicationFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JuryApplicationFiles.
   */
  distinct?: Prisma.JuryApplicationFileScalarFieldEnum | Prisma.JuryApplicationFileScalarFieldEnum[]
}

/**
 * JuryApplicationFile findFirstOrThrow
 */
export type JuryApplicationFileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileInclude<ExtArgs> | null
  /**
   * Filter, which JuryApplicationFile to fetch.
   */
  where?: Prisma.JuryApplicationFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JuryApplicationFiles to fetch.
   */
  orderBy?: Prisma.JuryApplicationFileOrderByWithRelationInput | Prisma.JuryApplicationFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JuryApplicationFiles.
   */
  cursor?: Prisma.JuryApplicationFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JuryApplicationFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JuryApplicationFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JuryApplicationFiles.
   */
  distinct?: Prisma.JuryApplicationFileScalarFieldEnum | Prisma.JuryApplicationFileScalarFieldEnum[]
}

/**
 * JuryApplicationFile findMany
 */
export type JuryApplicationFileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileInclude<ExtArgs> | null
  /**
   * Filter, which JuryApplicationFiles to fetch.
   */
  where?: Prisma.JuryApplicationFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JuryApplicationFiles to fetch.
   */
  orderBy?: Prisma.JuryApplicationFileOrderByWithRelationInput | Prisma.JuryApplicationFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing JuryApplicationFiles.
   */
  cursor?: Prisma.JuryApplicationFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JuryApplicationFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JuryApplicationFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JuryApplicationFiles.
   */
  distinct?: Prisma.JuryApplicationFileScalarFieldEnum | Prisma.JuryApplicationFileScalarFieldEnum[]
}

/**
 * JuryApplicationFile create
 */
export type JuryApplicationFileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileInclude<ExtArgs> | null
  /**
   * The data needed to create a JuryApplicationFile.
   */
  data: Prisma.XOR<Prisma.JuryApplicationFileCreateInput, Prisma.JuryApplicationFileUncheckedCreateInput>
}

/**
 * JuryApplicationFile createMany
 */
export type JuryApplicationFileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many JuryApplicationFiles.
   */
  data: Prisma.JuryApplicationFileCreateManyInput | Prisma.JuryApplicationFileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * JuryApplicationFile createManyAndReturn
 */
export type JuryApplicationFileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * The data used to create many JuryApplicationFiles.
   */
  data: Prisma.JuryApplicationFileCreateManyInput | Prisma.JuryApplicationFileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * JuryApplicationFile update
 */
export type JuryApplicationFileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileInclude<ExtArgs> | null
  /**
   * The data needed to update a JuryApplicationFile.
   */
  data: Prisma.XOR<Prisma.JuryApplicationFileUpdateInput, Prisma.JuryApplicationFileUncheckedUpdateInput>
  /**
   * Choose, which JuryApplicationFile to update.
   */
  where: Prisma.JuryApplicationFileWhereUniqueInput
}

/**
 * JuryApplicationFile updateMany
 */
export type JuryApplicationFileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update JuryApplicationFiles.
   */
  data: Prisma.XOR<Prisma.JuryApplicationFileUpdateManyMutationInput, Prisma.JuryApplicationFileUncheckedUpdateManyInput>
  /**
   * Filter which JuryApplicationFiles to update
   */
  where?: Prisma.JuryApplicationFileWhereInput
  /**
   * Limit how many JuryApplicationFiles to update.
   */
  limit?: number
}

/**
 * JuryApplicationFile updateManyAndReturn
 */
export type JuryApplicationFileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * The data used to update JuryApplicationFiles.
   */
  data: Prisma.XOR<Prisma.JuryApplicationFileUpdateManyMutationInput, Prisma.JuryApplicationFileUncheckedUpdateManyInput>
  /**
   * Filter which JuryApplicationFiles to update
   */
  where?: Prisma.JuryApplicationFileWhereInput
  /**
   * Limit how many JuryApplicationFiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * JuryApplicationFile upsert
 */
export type JuryApplicationFileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileInclude<ExtArgs> | null
  /**
   * The filter to search for the JuryApplicationFile to update in case it exists.
   */
  where: Prisma.JuryApplicationFileWhereUniqueInput
  /**
   * In case the JuryApplicationFile found by the `where` argument doesn't exist, create a new JuryApplicationFile with this data.
   */
  create: Prisma.XOR<Prisma.JuryApplicationFileCreateInput, Prisma.JuryApplicationFileUncheckedCreateInput>
  /**
   * In case the JuryApplicationFile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.JuryApplicationFileUpdateInput, Prisma.JuryApplicationFileUncheckedUpdateInput>
}

/**
 * JuryApplicationFile delete
 */
export type JuryApplicationFileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileInclude<ExtArgs> | null
  /**
   * Filter which JuryApplicationFile to delete.
   */
  where: Prisma.JuryApplicationFileWhereUniqueInput
}

/**
 * JuryApplicationFile deleteMany
 */
export type JuryApplicationFileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JuryApplicationFiles to delete
   */
  where?: Prisma.JuryApplicationFileWhereInput
  /**
   * Limit how many JuryApplicationFiles to delete.
   */
  limit?: number
}

/**
 * JuryApplicationFile without action
 */
export type JuryApplicationFileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JuryApplicationFile
   */
  select?: Prisma.JuryApplicationFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JuryApplicationFile
   */
  omit?: Prisma.JuryApplicationFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JuryApplicationFileInclude<ExtArgs> | null
}
