import { trainingFormatOptions } from "@/features/applications/config/application-timeline";
import {
  imageAndPdf,
  imageOnly,
  optionalCertificates,
  optionalTestimonials,
  pdfOnly,
  pressFields,
} from "@/features/applications/config/direction-field-configs/common";
import type { ApplyFieldConfig } from "@/features/applications/types/application.types";

export const categoryFieldConfigs: Record<string, ApplyFieldConfig[]> = {
  hair: [
    {
      key: "portfolioPhotos",
      label: "Portfolio Photos",
      type: "file",
      required: true,
      description: "Upload 5 to 20 portfolio images.",
      accept: imageOnly,
      minFiles: 5,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "beforeAfterPhotos",
      label: "Before / After Photos",
      type: "file",
      required: true,
      description:
        "Upload paired before-and-after images in matching order.",
      accept: imageOnly,
      minFiles: 2,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "portfolioVideo",
      label: "Portfolio Video",
      type: "url",
      description: "Optional video link.",
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "signatureTechnique",
      label: "Signature Technique",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    {
      key: "sterilizationProtocol",
      label: "Sterilization & Hygiene Protocol",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    ...optionalTestimonials(),
    ...optionalCertificates(),
    ...pressFields(),
  ],
  nail: [
    {
      key: "portfolioPhotos",
      label: "Portfolio Photos",
      type: "file",
      required: true,
      description: "Upload 5 to 20 images.",
      accept: imageOnly,
      minFiles: 5,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "beforeAfterPhotos",
      label: "Before / After Photos",
      type: "file",
      description: "Optional before-and-after examples.",
      accept: imageOnly,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "portfolioVideo",
      label: "Portfolio Video",
      type: "url",
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "mostRequestedService",
      label: "Most Requested Service",
      type: "textarea",
      required: true,
      rows: 3,
      maxWords: 100,
      description: "Maximum 100 words.",
    },
    {
      key: "sterilizationProtocol",
      label: "Sterilization & Hygiene Protocol",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    ...optionalTestimonials(),
    ...optionalCertificates(),
    ...pressFields(),
  ],
  brow: [
    {
      key: "portfolioPhotos",
      label: "Portfolio Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 5,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "beforeAfterPhotos",
      label: "Before / After Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 2,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "portfolioVideo",
      label: "Portfolio Video",
      type: "url",
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "challengingCorrectionCase",
      label: "Challenging Correction Case",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    {
      key: "sterilizationProtocol",
      label: "Sterilization & Hygiene Protocol",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    ...optionalTestimonials(),
    ...optionalCertificates(),
  ],
  lash: [
    {
      key: "portfolioPhotos",
      label: "Portfolio Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 5,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "beforeAfterPhotos",
      label: "Before / After Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 2,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "portfolioVideo",
      label: "Portfolio Video",
      type: "url",
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "teachLashTechniques",
      label: "Do you teach lash techniques?",
      type: "radio",
      required: true,
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
    },
    {
      key: "teachingFormatReach",
      label: "Teaching Format & Reach",
      type: "textarea",
      rows: 4,
      maxWords: 200,
      required: true,
      description: "Maximum 200 words.",
      visibleWhen: {
        fieldKey: "teachLashTechniques",
        equals: "yes",
      },
    },
    {
      key: "sterilizationProtocol",
      label: "Sterilization & Hygiene Protocol",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    ...optionalTestimonials(),
    ...optionalCertificates(),
  ],
  "skin-cosmetology": [
    {
      key: "portfolioPhotos",
      label: "Portfolio Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 5,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "beforeAfterPhotos",
      label: "Before / After Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 2,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "portfolioVideo",
      label: "Portfolio Video",
      type: "url",
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "complexSkinCaseDescription",
      label: "Complex Skin Case Description",
      type: "textarea",
      required: true,
      rows: 5,
      maxWords: 300,
      description: "Maximum 300 words.",
    },
    {
      key: "sterilizationProtocol",
      label: "Sterilization & Hygiene Protocol",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    {
      key: "professionalEquipmentDevices",
      label: "Professional Equipment / Devices",
      type: "textarea",
      required: true,
      rows: 3,
      maxWords: 100,
      description: "Maximum 100 words.",
    },
    ...optionalTestimonials(),
    ...optionalCertificates(),
    {
      key: "publishedArticlesResearchUrl",
      label: "Published Articles / Research URL",
      type: "url",
    },
    {
      key: "publishedArticlesResearchFiles",
      label: "Published Articles / Research Files",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 3,
      maxFileSizeMb: 5,
    },
  ],
  "facial-treatments": [
    {
      key: "portfolioPhotos",
      label: "Portfolio Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 5,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "beforeAfterPhotos",
      label: "Before / After Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 2,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "productsDevicesUsed",
      label: "Products & Devices Used",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    {
      key: "sterilizationProtocol",
      label: "Sterilization & Hygiene Protocol",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    ...optionalTestimonials(),
    {
      key: "advancedTrainingCertificates",
      label: "Advanced Training Certificates",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
  ],
  "makeup-artistry": [
    {
      key: "portfolioPhotos",
      label: "Portfolio Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 5,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "editorialBridalPortfolio",
      label: "Editorial / Bridal Portfolio",
      type: "file",
      required: true,
      accept: imageAndPdf,
      minFiles: 1,
      maxFiles: 10,
      maxFileSizeMb: 5,
    },
    {
      key: "portfolioVideo",
      label: "Portfolio Video",
      type: "url",
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "clientUnderstandingApproach",
      label: "Client Understanding Approach",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    {
      key: "publishedEditorialWorkUrl",
      label: "Published / Editorial Work URL",
      type: "url",
    },
    {
      key: "publishedEditorialWorkFiles",
      label: "Published / Editorial Work Files",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
    ...optionalTestimonials(),
    ...optionalCertificates(),
  ],
  "permanent-makeup": [
    {
      key: "portfolioPhotos",
      label: "Portfolio Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 5,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "beforeAfterPhotos",
      label: "Before / After Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 2,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "portfolioVideo",
      label: "Portfolio Video",
      type: "url",
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "colorTheoryApproach",
      label: "Color Theory & Skin Tone Approach",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    {
      key: "sterilizationProtocol",
      label: "Sterilization & Hygiene Protocol",
      type: "textarea",
      required: true,
      rows: 5,
      maxWords: 250,
      description: "Maximum 250 words.",
    },
    {
      key: "bloodbornePathogenCertificate",
      label: "Bloodborne Pathogen Certificate",
      type: "file",
      required: true,
      accept: imageAndPdf,
      minFiles: 1,
      maxFiles: 2,
      maxFileSizeMb: 5,
    },
    {
      key: "clientConsentFormSample",
      label: "Client Consent Form (Anonymized Sample)",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 2,
      maxFileSizeMb: 5,
    },
    ...optionalTestimonials(),
    ...optionalCertificates(),
  ],
  "body-wellness": [
    {
      key: "portfolioMediaFiles",
      label: "Portfolio Photos / Video",
      type: "file",
      required: true,
      accept: imageAndPdf,
      minFiles: 1,
      maxFiles: 10,
      maxFileSizeMb: 5,
      description: "Upload supporting media files.",
    },
    {
      key: "portfolioMediaUrl",
      label: "Portfolio Video URL",
      type: "url",
      description: "Optional external media link.",
    },
    {
      key: "beforeAfterPhotos",
      label: "Before / After Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 2,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "treatmentEffectivenessMeasurement",
      label: "Treatment Effectiveness Measurement",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    {
      key: "sterilizationProtocol",
      label: "Sterilization & Hygiene Protocol",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    ...optionalTestimonials(),
    ...optionalCertificates(),
  ],
  education: [
    {
      key: "studentWorkPhotos",
      label: "Portfolio: Student Work Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 5,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "photosWithStudents",
      label: "Photos with Students",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 2,
      maxFiles: 10,
      maxFileSizeMb: 5,
    },
    {
      key: "teachingVideoDemo",
      label: "Teaching Video / Demo",
      type: "url",
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "studentsTrainedLastTwoYears",
      label: "Number of Students Trained (2 Years)",
      type: "number",
      required: true,
      min: 1,
    },
    {
      key: "trainingFormat",
      label: "Training Format",
      type: "checkbox-group",
      required: true,
      options: trainingFormatOptions,
      description: "Select all formats that apply.",
    },
    {
      key: "courseCurriculumSyllabus",
      label: "Course Curriculum / Syllabus",
      type: "file",
      required: true,
      accept: pdfOnly,
      minFiles: 1,
      maxFiles: 1,
      maxFileSizeMb: 5,
    },
    {
      key: "studentTestimonialsText",
      label: "Student Testimonials",
      type: "textarea",
      required: true,
      rows: 4,
      description:
        "Provide written testimonials here, or upload files below, or both.",
    },
    {
      key: "studentTestimonialsFiles",
      label: "Student Testimonials Files",
      type: "file",
      required: true,
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
      description: "Upload up to 5 files if available.",
    },
    {
      key: "graduateAchievements",
      label: "Graduate Achievements",
      type: "textarea",
      rows: 4,
      maxWords: 200,
      description: "Optional, maximum 200 words.",
    },
    {
      key: "onlinePlatformLms",
      label: "Online Platform / LMS",
      type: "url",
    },
    {
      key: "sterilizationCoveredInCurriculum",
      label: "Sterilization Covered in Curriculum?",
      type: "radio",
      required: true,
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
    },
    {
      key: "sterilizationModuleDescription",
      label: "Sterilization Module Description",
      type: "textarea",
      required: true,
      rows: 3,
      maxWords: 100,
      description: "Maximum 100 words.",
      visibleWhen: {
        fieldKey: "sterilizationCoveredInCurriculum",
        equals: "yes",
      },
    },
    {
      key: "educatorProfessionalCertifications",
      label: "Professional Certifications (Yours)",
      type: "file",
      required: true,
      accept: imageAndPdf,
      minFiles: 1,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
    {
      key: "publishedEducationalMaterialsUrl",
      label: "Published Educational Materials URL",
      type: "url",
    },
    {
      key: "publishedEducationalMaterialsFiles",
      label: "Published Educational Materials Files",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
  ],
  salon: [
    {
      key: "salonInteriorPhotos",
      label: "Salon Interior Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 3,
      maxFiles: 15,
      maxFileSizeMb: 5,
    },
    {
      key: "teamPhotos",
      label: "Team Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 2,
      maxFiles: 10,
      maxFileSizeMb: 5,
    },
    {
      key: "serviceMenuPortfolioUrl",
      label: "Service Menu / Portfolio URL",
      type: "url",
      description: "Provide a link and/or upload a PDF below.",
    },
    {
      key: "serviceMenuPortfolioFile",
      label: "Service Menu / Portfolio PDF",
      type: "file",
      required: true,
      accept: pdfOnly,
      minFiles: 1,
      maxFiles: 1,
      maxFileSizeMb: 5,
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "numberOfMasters",
      label: "Number of Masters / Specialists",
      type: "number",
      required: true,
      min: 1,
    },
    {
      key: "annualClientVolume",
      label: "Annual Client Volume (Approx.)",
      type: "number",
      required: true,
      min: 1,
    },
    {
      key: "googleYelpReviewsLink",
      label: "Google / Yelp Reviews Link",
      type: "url",
      required: true,
    },
    {
      key: "averageRating",
      label: "Average Rating",
      type: "number",
      required: true,
      min: 1,
      max: 5,
    },
    {
      key: "totalNumberOfReviews",
      label: "Total Number of Reviews",
      type: "number",
      required: true,
      min: 1,
    },
    {
      key: "onlineBookingSystem",
      label: "Online Booking System",
      type: "url",
    },
    {
      key: "sterilizationProtocol",
      label: "Sterilization & Hygiene Protocol",
      type: "textarea",
      required: true,
      rows: 5,
      maxWords: 250,
      description: "Maximum 250 words.",
    },
    ...optionalTestimonials(),
    {
      key: "pressMediaCoverageUrl",
      label: "Press / Media Coverage URL",
      type: "url",
    },
    {
      key: "pressMediaCoverageFiles",
      label: "Press / Media Coverage Files",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
    {
      key: "businessLicensePermit",
      label: "Business License / Permit",
      type: "file",
      required: true,
      accept: imageAndPdf,
      minFiles: 1,
      maxFiles: 2,
      maxFileSizeMb: 5,
    },
  ],
  brand: [
    {
      key: "productPhotos",
      label: "Product Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 3,
      maxFiles: 15,
      maxFileSizeMb: 5,
    },
    {
      key: "brandPackagingVideo",
      label: "Brand / Packaging Video",
      type: "url",
    },
    {
      key: "statementOfAchievements",
      label: "Statement of Achievements",
      type: "textarea",
      required: true,
      rows: 6,
      maxWords: 500,
      description: "Maximum 500 words.",
    },
    {
      key: "brandRegistrationDocument",
      label: "Brand Registration Document",
      type: "file",
      required: true,
      accept: pdfOnly,
      minFiles: 1,
      maxFiles: 1,
      maxFileSizeMb: 5,
    },
    {
      key: "laboratoryTestingResults",
      label: "Laboratory Testing Results",
      type: "file",
      required: true,
      accept: pdfOnly,
      minFiles: 1,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
    {
      key: "safetyComplianceCertificate",
      label: "Safety / Compliance Certificate",
      type: "file",
      required: true,
      accept: imageAndPdf,
      minFiles: 1,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
    {
      key: "distributionChannels",
      label: "Distribution Channels",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    {
      key: "professionalIndustryFeedback",
      label: "Professional Industry Feedback",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    {
      key: "pressMediaFeaturesUrl",
      label: "Press / Media Features URL",
      type: "url",
    },
    {
      key: "pressMediaFeaturesFiles",
      label: "Press / Media Features Files",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
    {
      key: "industryPartnerships",
      label: "Industry Partnerships",
      type: "textarea",
      rows: 3,
      maxWords: 100,
      description: "Optional, maximum 100 words.",
    },
    ...optionalTestimonials("Client / Professional Testimonials"),
    {
      key: "ingredientFormulaDisclosure",
      label: "Ingredient List / Formula Disclosure",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
  ],
};
