import { trainingFormatOptions } from "@/features/applications/config/application-timeline";
import {
  imageAndPdf,
  imageOnly,
  optionalCertificates,
  pdfOnly,
  pressFields,
} from "@/features/applications/config/category-field-configs/common";
import type { ApplyFieldConfig } from "@/features/applications/types/application.types";

const statementOfAchievementsField: ApplyFieldConfig = {
  key: "statementOfAchievements",
  label: "Statement of Achievements",
  type: "textarea",
  required: true,
  rows: 6,
  maxWords: 500,
  description: "Maximum 500 words.",
  placeholder:
    "List all your professional credentials: whether you are a judge, media publications about you, awards, achievements, championship participation, publications, certificates, and any other professional merits.",
};

const signatureTechniqueField: ApplyFieldConfig = {
  key: "signatureTechnique",
  label: "Signature Technique",
  type: "textarea",
  required: true,
  rows: 4,
  maxWords: 200,
  description: "Maximum 200 words.",
  placeholder:
    "Describe all techniques you work with, your experience, specialization, signature techniques, and the areas in which you have studied or taught.",
};

const sterilizationProtocolField: ApplyFieldConfig = {
  key: "sterilizationProtocol",
  label: "Sterilization & Hygiene Protocol",
  type: "textarea",
  required: true,
  rows: 4,
  maxWords: 200,
  description: "Maximum 200 words.",
  placeholder:
    "Briefly describe how you follow sterilization, disinfection, and hygiene rules in your workspace: tool processing, use of disposable materials, sanitary standards, and keeping the workplace clean.",
};

const practitionerBlockBFields: ApplyFieldConfig[] = [
  {
    key: "portfolioPhotos",
    label: "Portfolio Photos",
    type: "file",
    required: true,
    description: "Upload 5 to 20 portfolio images.",
    accept: imageOnly,
    minFiles: 5,
    maxFiles: 20,
    maxFileSizeMb: 5,
  },
  {
    key: "beforeAfterPhotos",
    label: "Before / After Photos",
    type: "file",
    required: true,
    description: "Upload paired before-and-after images in matching order.",
    accept: imageOnly,
    minFiles: 2,
    maxFiles: 20,
    maxFileSizeMb: 5,
  },
  {
    key: "portfolioVideo",
    label: "Portfolio Video",
    type: "url",
    description: "Optional video link.",
  },
  statementOfAchievementsField,
  signatureTechniqueField,
  sterilizationProtocolField,
  ...optionalCertificates(),
  ...pressFields(),
];

export const categoryFieldConfigs: Record<string, ApplyFieldConfig[]> = {
  hair: practitionerBlockBFields,
  nail: practitionerBlockBFields,
  brow: practitionerBlockBFields,
  lash: practitionerBlockBFields,
  "skin-cosmetology-facial": practitionerBlockBFields,
  "makeup-artistry": practitionerBlockBFields,
  "permanent-makeup": practitionerBlockBFields,
  "body-wellness-nutrition": practitionerBlockBFields,
  // Legacy slugs kept for backward-compatible admin/jury rendering.
  "skin-cosmetology": practitionerBlockBFields,
  "facial-treatments": practitionerBlockBFields,
  "body-wellness": practitionerBlockBFields,
  education: [
    {
      key: "studentWorkPhotos",
      label: "Portfolio: Student Work Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 5,
      maxFiles: 20,
      maxFileSizeMb: 5,
    },
    {
      key: "photosWithStudents",
      label: "Photos with Students",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 2,
      maxFiles: 10,
      maxFileSizeMb: 5,
    },
    {
      key: "teachingVideoDemo",
      label: "Teaching Video / Demo",
      type: "url",
    },
    statementOfAchievementsField,
    {
      key: "studentsTrainedLastTwoYears",
      label: "Number of Students Trained (2 Years)",
      type: "number",
      required: true,
      min: 1,
    },
    {
      key: "trainingFormat",
      label: "Training Format",
      type: "checkbox-group",
      required: true,
      options: trainingFormatOptions,
      description: "Select all formats that apply.",
    },
    {
      key: "courseCurriculumSyllabus",
      label: "Course Curriculum / Syllabus",
      type: "file",
      required: true,
      accept: pdfOnly,
      minFiles: 1,
      maxFiles: 1,
      maxFileSizeMb: 5,
    },
    {
      key: "studentTestimonialsText",
      label: "Student Testimonials",
      type: "textarea",
      required: true,
      rows: 4,
      description:
        "Provide written testimonials here, or upload files below, or both.",
    },
    {
      key: "studentTestimonialsFiles",
      label: "Student Testimonials Files",
      type: "file",
      required: true,
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
      description: "Upload up to 5 files if available.",
    },
    {
      key: "graduateAchievements",
      label: "Graduate Achievements",
      type: "textarea",
      rows: 4,
      maxWords: 200,
      description: "Optional, maximum 200 words.",
    },
    {
      key: "onlinePlatformLms",
      label: "Online Platform / LMS",
      type: "url",
    },
    {
      key: "sterilizationCoveredInCurriculum",
      label: "Sterilization Covered in Curriculum?",
      type: "radio",
      required: true,
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
    },
    {
      key: "sterilizationModuleDescription",
      label: "Sterilization Module Description",
      type: "textarea",
      required: true,
      rows: 3,
      maxWords: 100,
      description: "Maximum 100 words.",
      visibleWhen: {
        fieldKey: "sterilizationCoveredInCurriculum",
        equals: "yes",
      },
    },
    {
      key: "educatorProfessionalCertifications",
      label: "Professional Certifications (Yours)",
      type: "file",
      required: true,
      accept: imageAndPdf,
      minFiles: 1,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
    {
      key: "publishedEducationalMaterialsUrl",
      label: "Published Educational Materials URL",
      type: "url",
    },
    {
      key: "publishedEducationalMaterialsFiles",
      label: "Published Educational Materials Files",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
  ],
  salon: [
    {
      key: "salonInteriorPhotos",
      label: "Salon Interior Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 3,
      maxFiles: 15,
      maxFileSizeMb: 5,
    },
    {
      key: "teamPhotos",
      label: "Team Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 2,
      maxFiles: 10,
      maxFileSizeMb: 5,
    },
    {
      key: "serviceMenuPortfolioUrl",
      label: "Service Menu / Portfolio URL",
      type: "url",
      description: "Provide a link and/or upload a PDF below.",
    },
    {
      key: "serviceMenuPortfolioFile",
      label: "Service Menu / Portfolio PDF",
      type: "file",
      required: true,
      accept: pdfOnly,
      minFiles: 1,
      maxFiles: 1,
      maxFileSizeMb: 5,
    },
    statementOfAchievementsField,
    {
      key: "numberOfMasters",
      label: "Number of Masters / Specialists",
      type: "number",
      required: true,
      min: 1,
    },
    {
      key: "annualClientVolume",
      label: "Annual Client Volume (Approx.)",
      type: "number",
      required: true,
      min: 1,
    },
    {
      key: "googleYelpReviewsLink",
      label: "Google / Yelp Reviews Link",
      type: "url",
      required: true,
    },
    {
      key: "averageRating",
      label: "Average Rating",
      type: "number",
      required: true,
      min: 1,
      max: 5,
    },
    {
      key: "totalNumberOfReviews",
      label: "Total Number of Reviews",
      type: "number",
      required: true,
      min: 1,
    },
    {
      key: "onlineBookingSystem",
      label: "Online Booking System",
      type: "url",
    },
    sterilizationProtocolField,
    {
      key: "pressMediaCoverageUrl",
      label: "Press / Media Coverage URL",
      type: "url",
    },
    {
      key: "pressMediaCoverageFiles",
      label: "Press / Media Coverage Files",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
    {
      key: "businessLicensePermit",
      label: "Business License / Permit",
      type: "file",
      required: true,
      accept: imageAndPdf,
      minFiles: 1,
      maxFiles: 2,
      maxFileSizeMb: 5,
    },
  ],
  brand: [
    {
      key: "productPhotos",
      label: "Product Photos",
      type: "file",
      required: true,
      accept: imageOnly,
      minFiles: 3,
      maxFiles: 15,
      maxFileSizeMb: 5,
    },
    {
      key: "brandPackagingVideo",
      label: "Brand / Packaging Video",
      type: "url",
    },
    statementOfAchievementsField,
    {
      key: "brandRegistrationDocument",
      label: "Brand Registration Document",
      type: "file",
      required: true,
      accept: pdfOnly,
      minFiles: 1,
      maxFiles: 1,
      maxFileSizeMb: 5,
    },
    {
      key: "laboratoryTestingResults",
      label: "Laboratory Testing Results",
      type: "file",
      required: true,
      accept: pdfOnly,
      minFiles: 1,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
    {
      key: "safetyComplianceCertificate",
      label: "Safety / Compliance Certificate",
      type: "file",
      required: true,
      accept: imageAndPdf,
      minFiles: 1,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
    {
      key: "distributionChannels",
      label: "Distribution Channels",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    {
      key: "professionalIndustryFeedback",
      label: "Professional Industry Feedback",
      type: "textarea",
      required: true,
      rows: 4,
      maxWords: 200,
      description: "Maximum 200 words.",
    },
    {
      key: "pressMediaFeaturesUrl",
      label: "Press / Media Features URL",
      type: "url",
    },
    {
      key: "pressMediaFeaturesFiles",
      label: "Press / Media Features Files",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
    {
      key: "industryPartnerships",
      label: "Industry Partnerships",
      type: "textarea",
      rows: 3,
      maxWords: 100,
      description: "Optional, maximum 100 words.",
    },
    {
      key: "ingredientFormulaDisclosure",
      label: "Ingredient List / Formula Disclosure",
      type: "file",
      accept: imageAndPdf,
      maxFiles: 5,
      maxFileSizeMb: 5,
    },
  ],
};
